---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - prometheus-rule.yaml
  - pod-monitors.yaml
  - receiver
configMapGenerator:
  - name: flux-instance-values
    files:
      - values.yaml=helm/values.yaml
configurations:
  - helm/kustomizeconfig.yaml
