apiVersion: v1
kind: Secret
metadata:
  name: sops-age-secret
stringData:
  age.agekey: ENC[AES256_GCM,data:bDhIObpg/xxCJg0V7S/CWBOfnfB1bcAzoGfqd8XhOOqhtynLdIVdI9caMsQ/8IpeP9BxXGbeKDHCahn2cFn5wJGQpWg+UPKNc40=,iv:LZ2rd+DyL2/qM2uahyMl4sK+kmdISuaY8An8Ifpy9BM=,tag:JMDz8+DvvtTBwP3AzAuADw==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZTVYYVFHa211MkhrMk9G
        UzhHWDdraXgxYWxNNWVDdDl3anpEZHZmVEFrClVLeUwxUXhVekx1UkVQWXV2TVV6
        YTVyZWdDQ2l6RUc2aWVFbTBiaWttNmcKLS0tIE5ZWU5SNFdqcnNzU0NzTjd0UjND
        d0hCa1ZnTGhZQWJXYytRWG5RL21vVkEKi7TGKcGBgp8BhOxn7jUkm33KJKfg19aU
        1/Fzz9ntDtuDrIk9zL1FuLDTlv4b/73hePf7F4tKDvzpIr68mGxKDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T21:34:19Z"
  mac: ENC[AES256_GCM,data:vcMWvT/CCP9LhhACnjELUwl+5HmPS00agmlNjZT5etlP8smle85EJ2DPk6btq5tfhmqskYirnbHPHfgHFtc1XhZ3lFzEig8tGkIn+jKnF0QEDTH2FK0d/nexhGBAPWOCBb+/JWqokKPgZtUg8VEK5ImG/NdBXseZvpKElnkerMI=,iv:FHbsRc/wnyMIWWdJLWSmOKJSL6m9Gep0RbN0vwgiYeU=,tag:btMZ4i3+fydPMVHg2aZZdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
