apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  CF_API_TOKEN: ENC[AES256_GCM,data:EzYF/+EL/tcmH/QwZ1CKnuGDJLBOsboZIXBUIfw3FUnHnKvyKNpk9Q==,iv:Mz4V2Fuvh/ENjOC8+a4FM0D67qh4/PDJ+APU1g5PqZo=,tag:UK6Fa/7NUv9eFIKRJ0hR1Q==,type:str]
  CF_ZONE_ID: ENC[AES256_GCM,data:np/+gG8jptWnX+WLMmv/K4PCIP6LndQr6IFUMRVrKYI=,iv:R//D151U4kZQVsQD2Y0N7XYVeVLM4DooTMG8zuq5PJY=,tag:ZlegRwj3Md4DrHnrNinZwg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OC9jaDBlRkdoSTZEM01B
        VWc3YllMbXdINm1lMERENjYzcDR6OTVLZmpRCkVUdUkyWE5lbnR6MEtwbkxZMkFr
        QjB1cFlLWEZTckVqSDF6MkVoZ0szUncKLS0tIHlIMUJSSVViSGVCTEZwK296endH
        S3ZJV0RVdjUxSkJybWxvTDBGb3d4SEkKyj3Z6vcVzmmkmWHB7FJlaVrLVt3U2ah1
        qgPdGWdv3Yml9XsEDf61nyewqRYqHU52AVr4hW1BpNAjH10jJprCcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T11:58:12Z"
  mac: ENC[AES256_GCM,data:2rfWH8gsExpelQsZd4RXFGo98gNJcNoVNtIu2fX6BTUQcodq19V32KDOdkRZe38NWhFjqpDoujdHdpELZzjGd3VU7eNlZfXaor0aq3+B2EYfcqLWd7+7ety+nhYIDv5naevfWT6PPfhYnyZsmo6xdMZJ0sNFnZNOHwFf3TcT2tU=,iv:iVryg0tCQlhYARF/fRsxoIDdXFngTSOlj3dlMoX0h7E=,tag:7hatgbxz6SbtaPGyUx4c4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
