---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template

  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: &postgres-secret postgres-superuser
      valuesKey: username
      targetPath: postgres.POSTGRES_USER
    - kind: Secret
      name: *postgres-secret
      valuesKey: password
      targetPath: postgres.POSTGRES_PWD

  values:
    postgres: {}

    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/auto-setup
              tag: 1.28.1.0@sha256:607d68caa111338d754771efb876c92dfcdae06d056e4530bb31cd0f37406e6a
            env:
              DB: postgres12
              DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/dev-dynamic-config.yaml

              DBNAME: temporal
              DB_PORT: 5432
              POSTGRES_SEEDS: 'postgres-temporal-rw.{{ .Release.Namespace }}.svc.cluster.local'
              POSTGRES_USER: '{{ .Values.postgres.POSTGRES_USER }}'
              POSTGRES_PWD: '{{ .Values.postgres.POSTGRES_PWD }}'

      ui:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/ui
              tag: 2.43.2@sha256:2aa0180570c7f5440aa6495ee9230953f33b0a19a78d8339b41d02dbae25dec9
            env:
              TEMPORAL_ADDRESS: &temporalAddress temporal-server:7233
              TEMPORAL_CORS_ORIGINS: http://localhost:3000

      admin-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/admin-tools
              tag: 1.29@sha256:a3a52e6ca122fe47cc69dc1039ab82ac59fbf6d8b84003eb2557b5b1340e82e0
            env:
              TEMPORAL_ADDRESS: *temporalAddress

    service:
      server:
        primary: true
        controller: server
        ports:
          http:
            port: 7233
      ui:
        controller: ui
        ports:
          http:
            port: &uiHttpPort 8080

    route:
      ui:
        hostnames: [ 'temporal.talos.${DOMAIN_NAME}' ]
        parentRefs:
          - name: envoy
            namespace: envoy-system
        rules:
          - backendRefs:
              - identifier: ui
                port: *uiHttpPort

    persistence:
      dynamic-config:
        type: configMap
        name: temporal-configmap
        advancedMounts:
          server:
            app:
              - path: /etc/temporal/config/dynamicconfig
