---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: lldap-secret
    template:
      data:
        LLDAP_JWT_SECRET: '{{ .LLDAP_JWT_SECRET }}'
        LLDAP_SERVER_KEY_SEED: '{{ .LLDAP_SERVER_KEY_SEED }}'
        LLDAP_LDAP_USER_PASS: '{{ .LLDAP_LDAP_USER_PASS }}'
        LLDAP_USER_DN: '{{ .LLDAP_USER_DN }}'
        LLDAP_LDAP_USER_EMAIL: '{{ .LLDAP_LDAP_USER_EMAIL }}'

  dataFrom:
    - extract:
        key: lldap
