---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: your-spotify
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: your-spotify
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: your-spotify

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        seccompProfile: { type: RuntimeDefault }

    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/yooooomi/your_spotify_server
              tag: 1.18.0@sha256:80285f518dc8b6a8392986419503e1b804f62cc235d80fec6ce5e052264605ad
            env:
              TIMEZONE: ${TIMEZONE}

              API_ENDPOINT: &api_endpoint https://spotify.talos.${DOMAIN_NAME}/api
              CLIENT_ENDPOINT: https://spotify.talos.${DOMAIN_NAME}
              MONGO_ENDPOINT: 'mongodb://{{ .Release.Name }}-mongodb:27017/your_spotify'
              PORT: &port 80

            envFrom:
              - secretRef:
                  name: '{{ .Release.Name }}-secret'

            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true

            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ 'ALL' ] }

      web:
        containers:
          app:
            image:
              repository: ghcr.io/yooooomi/your_spotify_client
              tag: 1.18.0@sha256:e1379587e48a006e18b1eb3752bb6b6869f6518c29706d487f88083a1c8eab89

            env:
              TIMEZONE: ${TIMEZONE}
              API_ENDPOINT: *api_endpoint

            probes: *probes
            securityContext: *securityContext

      mongodb:
        type: statefulset
        statefulset:
          podManagementPolicy: OrderedReady

        containers:
          app:
            image:
              repository: docker.io/library/mongo
              tag: 6.0.4-focal

            probes: *probes

    service:
      server:
        controller: server
        primary: true
        ports:
          http:
            port: *port

      web:
        controller: web
        ports:
          http:
            port: &webport 3000

      mongodb:
        controller: mongodb
        ports:
          http:
            port: 27017

    route:
      app:
        hostnames:
          - 'spotify.talos.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system

        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: '/api'
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: '/'
            backendRefs:
              - identifier: server
                port: *port

          - matches:
              - path:
                  type: PathPrefix
                  value: '/'
            backendRefs:
              - identifier: web
                port: *webport

    persistence:
      config:
        existingClaim: '{{ .Release.Name }}'
        advancedMounts:
          mongodb:
            app:
              - path: /data/db
