---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: your-spotify
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: your-spotify
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: your-spotify

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }

    controllers:
      server:
        strategy: &strat RollingUpdate
        rollingUpdate: &ru
          unavailable: 0

        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: yooooomi/your_spotify_server
              tag: 1.17.0
            env:
              TIMEZONE: ${TIMEZONE}

              API_ENDPOINT: &api_endpoint https://spotify-api.talos.${DOMAIN_NAME}
              CLIENT_ENDPOINT: https://spotify.talos.${DOMAIN_NAME}
              MONGO_ENDPOINT: mongodb://your-spotify-mongodb:27017/your_spotify

            envFrom:
              - secretRef:
                  name: your-spotify-secret

            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true

            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ 'ALL' ] }

      web:
        strategy: *strat
        rollingUpdate: *ru

        containers:
          app:
            image:
              repository: yooooomi/your_spotify_client
              tag: 1.17.0

            env:
              TIMEZONE: ${TIMEZONE}
              API_ENDPOINT: *api_endpoint

            probes: *probes
            securityContext: *securityContext

      mongodb:
        type: statefulset
        rollingUpdate: *ru
        statefulset:
          podManagementPolicy: OrderedReady

        containers:
          app:
            image:
              repository: docker.io/library/mongo
              tag: 6.0.4-focal

            env:
              TZ: ${TIMEZONE}

            probes: *probes

    service:
      server:
        controllers: server
        ports:
          http:
            port: 8080
      web:
        controllers: web
        ports:
          http:
            port: 3000
      mongodb:
        controllers: mongodb
        ports:
          http:
            port: 27017
    route:
      server:
        hostnames:
          - 'spotify-api.talos.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system
      web:
        hostnames:
          - 'spotify.talos.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system

    persistence:
      config:
        existingClaim: your-spotify
        advancedMounts:
          mongodb:
            app:
              - path: /data/db
