---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cleanarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: cleanarr-secret
    template:
      data:
        PLEX_TOKEN: '{{ .PLEX_TOKEN }}'
        LIBRARY_NAMES: '{{ .PLEX_LIBRARY_NAMES }}'

  dataFrom:
    - extract:
        key: plex
