---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gitlab-status
spec:
  providerRef:
    name: gitlab-status

  eventSources:
    - kind: Kustomization
      name: '*'
