apiVersion: v1
kind: Secret
metadata:
  name: gitlab-provider-token
stringData:
  token: ENC[AES256_GCM,data:q2QfN+n+nTbPCeYY6aT1Wugn1SpvjhnAYdK28PCGNzqB0wHtOiwaCXpcogjAWp2VjDPG,iv:DlXuXTsItOOBqsLqUWxHNozyh6BC4s49HCJeLpkicUU=,tag:/8WYGdP8K1Sg63L6jOJQRA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY21XcGQxdzBWWlhFSEpS
        T3JIa2trd2ZSeXdPY0pFKzY1eGsrdU01VVZVClBTUjMzT2lIQVUzdGFKaUdVL2g0
        V0krMVR3S0RHS3VYSDExL09YcnNhMEEKLS0tIE94eGNxZjduSzBSN2k2S1IzMFBo
        eEJyRkZ4V1BhYWtlWXJKL0Voeitpd2sKV8NWGqf51nh481M3OiO1mp1EDA0Yb4D2
        VxqZ802x+rXYt1yE4d32rrcdOaRM3c3P3Lg55NLpYeb5/BXO/JoSEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T18:47:38Z"
  mac: ENC[AES256_GCM,data:ujJPz0NjQ3czXh3dS5BYuPa1Yfw4Ktm4WeSMZcwLumYTAeYiu2A0yZ51EPuw9MANpwtNzTRZJs9eZNHy6PsT+FLe+g9rWbvy0FAPS6pSBfeDUwHswNbvIBW2TLoBGZPe0goiRJ98Ry+QIOEjMj9c89TIyASVoX/mbxn6WJIWPpU=,iv:3JnEfnv0gMddclLijRyrhrY2ZVPpFEIvj5/C5ymrvWA=,tag:9+VbJLf3ESkEuQJsbMkJmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
