apiVersion: v1
kind: Secret
metadata:
  name: gitlab-provider-token
stringData:
  token: ENC[AES256_GCM,data:nwAJMtn9ipim6HPzzXtqNgAn0/ht3syfrtFQdJB77awWe5VnQwkbifzfFy7oixDcp4Xl,iv:PEVkKTQQu2UuqncjTFR6ZcyQiL8FYCMtClSCRa/qy/c=,tag:M7rGuWZopo0NbmOYe8jiGg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeGYwMDNIYTFGRjJMMWx1
        RkZtZDdSUWNIR2kxQXdjUExld2RLbE4yRldVCi9HeXVWd2UyMVllQ2hsZCtMVXJk
        L29jbGxUZ1hkVVRlMUEzdVBZR01RM3cKLS0tICtkQm8vNUxTelpncVdsMUhzRXZm
        REZhMDBSNFY4WkQxSjZGeU91N0NiSGcK4BhYmXmuXkyDw4cqZVnxztNfmmpP7u7J
        HE6Qv+rSs5FrwQE3uvzFoUDI1WmwQqMkGAsGn1DbTVf1RbcNyUdhfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-22T22:13:34Z"
  mac: ENC[AES256_GCM,data:RfJ4e8K/+iM4d/bGtG4AslfrK+MU8NGhDUpe9l+NXlXD+TlVMDEppgt2KflBvuJpMp3ydZ5CnsVyO0Q9JeJBM0dF2NL7hyeavznDcPqYXvmULG5d/rGntp4izGerfOPNChIDJoCVlLS57Gv8lrJyoISQ9i3kMmiUV0qBaJpM4HU=,iv:UnWu4EB7g6hwiB4p+C3D4hT5OiwVgFfZ7GuKjfmHbQM=,tag:Hq9bC0kA9hzlYGQVIvXgyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
