apiVersion: v1
kind: Secret
metadata:
  name: gitlab-provider-token
stringData:
  token: ENC[AES256_GCM,data:ceY+wWp3BdLkxcbcFL1DffXqclZvThGhyY0Qz8LlSE1qlrTgekh4zI+1Uw3YSderxiNpm/U=,iv:6nHLNgjELz5Ow9Zm4zszN+E0LCUN3KtJVXi3oADzDDI=,tag:22It+ImeonTCTk5x8fIBTA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK0hMN0s4Qkg5OW8zeDl2
        TDI3NjBsd003YlNnUm9VY05JOC85cHFnS1RRCjBUR0FSOGIzZUsveWVRbXFmU3lD
        d2s4S2RpN1Rjdk1kdHRSVURtdGdweTQKLS0tIG43RXlOcWl0aHRLN0R6Ym9PSEZs
        QVo5a1gyYkhmZzZKaWFPV1d0QUVvMFUKit5faG/rfpuC33trQyq0rbqWKapVK1kK
        xrAjeyslb4GRG1+RuaSTNiOeLY79MPHjjxyGaqOWdOq2Q+lbVqYtWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T20:56:45Z"
  mac: ENC[AES256_GCM,data:8CtFQyA0Igdj+V6C0P0EqFoByfplpBeMV9zsrIMNZdhpnYmFJVZfkT41cf+IyLqZupDRjbeWGroe0kR5PfwY7uZ05VeEhxUdQf/cHYJ6ZvsMCjp8RIM/OEYTbrj+udh9zixy7iFPCZB0Km4d1ENIPspTTBa+PxUm7DEamr1iicU=,iv:G/0/3rLEe9d0/ZbX7xaoF4DM5Fl0r8t935V57HyjOk4=,tag:KM8vd7fbaKOmX6JAnzhUEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
