---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
spec:
  # noinspection KubernetesUnknownValues
  accessModes:
    - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}

  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${PVC_NAME}-dst

  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:=5Gi}

  storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
