---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: '${PVC_NAME}-dst'
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once

  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce} # Use ReadOnlyMany for CephFS
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}

    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=8Gi}

    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true

    repository: ${PVC_NAME}-volsync-secret
    sourceIdentity:
      sourceName: '${PVC_NAME}-src'

    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
