---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: '${PVC_NAME}-src'
spec:
  sourcePVC: '${PVC_NAME}'

  trigger:
    schedule: 0 0/24 * * *

  kopia:
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn-snapshot}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=longhorn-snapclass}
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}

    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=5Gi}
    cacheStorageClassName: ${VOLSYNC_CACHE_SNAPSHOTCLASS:=openebs-hostpath}

    compression: zstd-fastest
    copyMethod: Snapshot

    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}

    parallelism: 2
    repository: ${PVC_NAME}-volsync-secret
    retain:
      hourly: 24
      daily: 7
      weekly: 5
