---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: '${PVC_NAME}-src'
spec:
  sourcePVC: '${PVC_NAME}'

  trigger:
    schedule: 0 0/24 * * *

  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce} # Use ReadOnlyMany for CephFS
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}

    compression: zstd-fastest
    copyMethod: Snapshot

    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}

    parallelism: 2
    repository: ${PVC_NAME}-volsync-secret
    retain:
      hourly: 24
      daily: 7
      weekly: 5
