apiVersion: v1
kind: Secret
metadata:
  name: ${PVC_NAME}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:s3WKPG00awN7k30=,iv:t4XHPFmEfAmfO8yspwqMq+Emk5uqhMQz8JfkLIB3Xqc=,tag:0VeZHdxUKMggEHkIXQ6DeQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:1S/D8Fgp2ywNIe39mV4W4mDwrQfn+pvJ,iv:2QCC1TkfW3skEBWQne2JnbFY1K0QFvptmVYgDgh1gho=,tag:vivSyPavmAY4Dpql1WT+tw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Z6vOOaD+JYAnUkyLuiMv7Tp+uFU10XyuGkVwdZzS6D1qQclysUlOqtIvEKnsUMraCtEzqzDy/oqKKq+LLwQ4YsI18GRduWnLvjsIppbpi8LsC34iwHykkQ==,iv:WkyQhDvyCy5LhdIkxPv0NgT+rmYVyFZ6F2a/hdaC2lg=,tag:A4hqA/xpW1Kr8rJ7lVwU9Q==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVlAreDcwcndVeS9VT0Ni
        S2FHZTRjYlRlUkFlV25uTk9SUmpUajR3TkVnCmg1TjF6K0MzUmVYNFFabnRoK1hK
        UlE3YnhxdjlYT3lOZkxCbXpKbDdoK3cKLS0tIEY0MmQzdEFlVU9wQ0xTWnhLYUJM
        V3pmRkFOK1U3YmUzaWNJTE9mTzVIQVEKq/NpETbrpNE/+oAHZol+PW/gF9IJM+cE
        /F6UXJSXu2PIV7L55WgQaP45bFh3solX7dmt52ZQIZPyaY35g1npxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T22:11:30Z"
  mac: ENC[AES256_GCM,data:kv/37Z66FuhSMR4/YAsNmA0Rq6wqI/kT7frNRnqONPd+VaiMPIhhYoPvPp5spJXbbXy6AQ2YVmPFPmQS1jZ62Jw2S7qNMhmME1rFxtrIKdJGE6qMVkrKWI/jIdWr36tx3w8JdvFzf0h6OitKJzXZGaewYZyk7EC8J4zlSZ6kXmc=,iv:q0sgykOJMLP849Lnrzgz4uDO7Gd3Uq6E8FMuIokH+cI=,tag:1qApW6WxGD+zYgJ9xPLmAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
