---
version: "3"

set:
  - pipefail
shopt:
  - globstar

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  CLUSTER_DIR: '{{.ROOT_DIR}}/cluster'
  SOPS_CONFIG_FILE: '{{.ROOT_DIR}}/.sops.yaml'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'

  TALHELPER_CLUSTER_DIR: '{{.TALOS_DIR}}/clusterconfig'
  TALOSCONFIG: '{{.TALHELPER_CLUSTER_DIR}}/talosconfig'
  TALOS_CLUSTER_NAME:
    sh: yq '.clusterName' < '{{.TALOS_DIR}}/talconfig.yaml'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '~/.config/sops/age/K3s-Flux.agekey'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  talos: .taskfiles/talos
  talos:helper: .taskfiles/talos-helper
  bootstrap: .taskfiles/bootstrap
  flux-local: .taskfiles/flux-local
  volsync: .taskfiles/volsync

tasks:
  default: task --list

  reconcile:
    desc: Reconcile flux git repository.
    cmd: flux reconcile source git talos-kubernetes

  wol:
    desc: Send wol packets to start talos cluster.
    vars:
      mac_addresses:
        sh: yq '.nodes[].networkInterfaces[0].deviceSelector.hardwareAddr' < '{{.TALOS_DIR}}/talconfig.yaml'
      interface:
        sh: "ip -o -4 addr show up | awk '$2 !~ /^(lo|docker|veth|br-|virbr|tailscale)/ {print $2; exit}'"
    cmds:
      - for:
          var: mac_addresses
        cmd: sudo etherwake -i {{.interface}} {{.ITEM}}

  bootstrap:
    desc: Bootstrap cluster.
    cmds:
      - task: bootstrap:talos
      - task: bootstrap:cilium
      - task: bootstrap:apps
