---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
  namespace: system-upgrade
spec:
  dependsOn:
    - name: tuppr

  prune: true
  wait: false
  interval: 1h
  path: cluster/infra/system-upgrade/upgrades
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
