---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.34.3

  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")

    - apiVersion: longhorn.io/v1beta2
      kind: Volume
      expr: |-
        status.robustness != "degraded"

    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.phase in ['Cluster in healthy state']

    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      expr: |-
        status.phase in ['Ready']
