---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitlab
  namespace: &namespace gitlab
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  dependsOn: [ ]

  postBuild:
    substitute:
      APP: *app

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true

  targetNamespace: *namespace
  path: cluster/apps/dev/gitlab/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
