apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
stringData:
  username: ENC[AES256_GCM,data:yyQMhOxQQUA=,iv:cONlMdXCzJZbrEZpkwJPtSS1UIEaHde6YXumaJhgAls=,tag:xq5IK1/DwYU2uecAV58Asg==,type:str]
  password: ENC[AES256_GCM,data:w/rReP0u915YbiNxFLz+cAUqXhqutqoft6srJ/8M+6jLTUm6+K2xTWKUMqtUEVurNYWxXvTC3jGh58PaWApuJY/zcBYMCWMLuq4jy7yc24J4/Lfkj8d00w==,iv:7VPU04LpFnG2NcyfAWhJbPeDmKAToEwrRG8D7dItTEA=,tag:at88t9TFCCZfIvoRbLQ1gA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TzRxS1oxOGNaWjdkUGtj
        akVSOXlDbUh2Q1F6RU0xWmlMSDBFUldCbkV3CkV4cGJTK2Nvdm9qL2YyMm00THZq
        dWt0NWdiUmdOb2VZWXZ5R0lwbEFJbTQKLS0tIGRkWXBxbENaV1RjaDl3R0QxYXF5
        V0hCT1pUY1JXdXF5cnJTdnpBVXREeHMK48/PkHoOwKjMSgT2xA/TYjdum2vd/3CK
        irZ5U5VtdE8sKbcT+5KJk/Y2oAa2YpLTfqBdS+iGUM7K/KHlvRaSJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T15:04:16Z"
  mac: ENC[AES256_GCM,data:yB61ooohyvRIn0/eo7aqtsvliNU3nxbEaOLBrCySy+L6/5tmD3elx/Lg0CNcJmvVSxOTE3FCRLFx8ongHeIjGVcjKtRNIMJOwLN9Pc14vaw5FsZqHH3GGCMivUWXIV6a1XSqp+clUgF3Pk2mR1KlXaEltM0Rqmzn/bqMTvc3K8Y=,iv:AbS83PAkgrWgib0wYazGqHXCnsD/razeyT0gfhi4oB4=,tag:5GpJxlm1lurzdNS7ojEb1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
