---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator
spec:
  prune: true
  wait: true
  interval: 1h
  path: cluster/infra/operators/dragonfly/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
