---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
# Defines BGP instances and peer configurations that are applied to multiple nodes.
metadata:
  name: l3-bgp-cluster-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: cilium
      localASN: 64514
      peers:
        - name: unifi
          peerASN: 64513
          peerAddress: 192.168.0.1
          peerConfigRef:
            name: unifi-l3-bgp-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
# A common set of BGP peering setting. It can be used across multiple peers.
metadata:
  name: unifi-l3-bgp-peer-config
spec:

  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120

  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.home.arpa/peer: unifi

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
# Defines prefixes that are injected into the BGP routing table.
metadata:
  name: unifi-l3-bgp-advertisement
  labels:
    bgp.home.arpa/peer: unifi
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses: [ "LoadBalancerIP" ]
      selector:
        matchExpressions:
          - { key: io.cilium/bgp, operator: NotIn, values: [ "deny", "false" ] }
          - { key: io.cilium/internal, operator: NotIn, values: [ "true" ] }
