---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - networks.yaml
  - bgp
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=helm/values.yaml
configurations:
  - helm/kustomizeconfig.yaml
