---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: irqbalance
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: irqbalance

  values:
    defaultPodOptions:
      hostIPC: true
      hostPID: true

    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/irqbalance
              tag: 1.9.4@sha256:6cc768c3f074c221412d56b341a19c8432f9a6d76eda0b346285f9c5e2d3b2cc

            env:
              IRQBALANCE_BANNED_CPULIST: 8-19 # 12-19 are E-cores
              # See: https://gist.github.com/gavinmcfall/ea6cb1233d3a300e9f44caf65a32d519

            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 128Mi

            securityContext:
              privileged: true

    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
