---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - cilium/ks.yaml
  - coredns/ks.yaml

  - spegel/ks.yaml
  - metrics-server/ks.yaml
  - snapshot-controller/ks.yaml

  - node-feature-discovery/ks.yaml
  - device-plugins
  #- multus/ks.yaml

  - descheduler/ks.yaml
  - ksgate/ks.yaml
  - reloader/ks.yaml
  - fstrim/ks.yaml

  - mailpit/ks.yaml
