---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/namespace
  - ../../components/flux/sops
  - ../../components/flux/common
resources:
  - cilium/ks.yaml
  - coredns/ks.yaml
  - spegel/ks.yaml
