---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres-immich
  annotations:
    kyverno.io/ignore: 'true'
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'

spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18

  instances: 1
  enablePDB: true

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  managed:
    roles:
      - name: immich
        ensure: present
        superuser: true
        login: true
        passwordSecret:
          name: immich-postgres-user


    services:
      disabledDefaultServices: [ 'ro', 'r' ]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-immich-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: postgres-immich.svc.talos.${DOMAIN_NAME}

            spec:
              type: LoadBalancer
              ipFamilyPolicy: PreferDualStack
              externalTrafficPolicy: Local

  postgresql:
    shared_preload_libraries: [ ]
      # - 'vectors.so'
    #- 'vchord.so'

    parameters:
      max_connections: '200'
      max_slot_wal_keep_size: 5GB
      shared_buffers: '128MB'

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  storage:
    size: 10Gi
    storageClass: openebs-hostpath
