---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres-immich
  annotations:
    kyverno.io/ignore: 'true'
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'

spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17-system-bookworm

  instances: 3
  enablePDB: true

  enableSuperuserAccess: false

  postgresql:
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg17-v1.0.0
        dynamic_library_path:
          - /usr/lib/postgresql/17/lib/
        extension_control_path:
          - /usr/share/postgresql/17/

    shared_preload_libraries:
      - 'vchord'

    parameters:
      max_connections: '200'
      max_slot_wal_keep_size: 5GB
      shared_buffers: '128MB'

  bootstrap:
    #    initdb:
    #      database: immich
    #      owner: immich
    #
    #      dataChecksums: true
    #
    #      secret:
    #        name: postgres-immich-secret
    #
    #      postInitSQL:
    #        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;

    recovery:
      source: source

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: *name

  resources:
    requests:
      memory: '512Mi'

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  managed:
    services:
      disabledDefaultServices: [ 'ro', 'r' ]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-immich-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: postgres-immich.svc.talos.${DOMAIN_NAME}

            spec:
              type: LoadBalancer
              ipFamilyPolicy: PreferDualStack
              externalTrafficPolicy: Local
