---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
spec:
  cluster:
    name: postgres-immich

  name: immich
  owner: immich

  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
