---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-immich-daily
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-immich

  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
