apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
stringData:
  username: ENC[AES256_GCM,data:L3BXOS4t,iv:3Gi0M99CEOahZIOPjmvzJZI3JJDoXZaeyVCfgYRGyeE=,tag:hU7RZ+Vd7dM5417MsE+uYw==,type:str]
  password: ENC[AES256_GCM,data:c4gjZsrMOfU/VDpy/zw6H8Ge7XkcS9jvf1VkP9+RMZ+7zvSDxCp135x6nloTZoXBOrA6YU4Tv30X++OaNnjBNp6UhaOwu1tU4bGozmtzaJQhB2HsC29+Sg==,iv:fKzWDgSIO7QAHG5MvejwB+nyf1CyEChIRMOMHzEJbRU=,tag:bt7xdsc69ZeGBleb2fQKhw==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZUVIeG9lTm1SdGhIVWJi
        anByRFl1aXk3K0dxV05LNWhsUXhzSnFTSVZJCjZVZW4wbkNscWN4ZUxhMzFrd2VE
        VndFc1ZrTXNSYlFYbzlpeFhDdGtDV0EKLS0tIFQ4bW5VaURTLzc0UldhT3RjQjRt
        OGhxT1h4WFZvN3RFZUpLZjhsS21jdWsKKkN472U+fUbyRUVnDLRcUL275ZaMZ8wa
        RD1qcBUl7OTHWyRT2fNyQ2bPNvf162Aszh9eDN11XhWOxEY2hpyxlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T01:35:56Z"
  mac: ENC[AES256_GCM,data:ErEFqfGI1psPFTqgLgruHV0W7vyts6jvT/VwKrLh2VilUOEY2ioWUGN5WlR3YeE1i6LeLMqKzFZorQ4yBs6T3J5cxTlWDuXeukzjUA0InNMrxwFH94uZxn3CaqBR2+lalai+CVOPh+eJCvDUum7W8Ja0roSprzBohwM6p7fSoeU=,iv:p/RSEeGxkcUYQchqyodNLHUVcyGn5FQKe4Wfr+EgiYc=,tag:8tXwscTwprk6gn1NP9FoFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
