apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich-secret
stringData:
  username: ENC[AES256_GCM,data:8Q5zTRuD,iv:0obbUtMtiqgm4oU66vIee3eOE7cWSxTo5B1+rS9O4GE=,tag:4qxfu08xNwWRTFS55d2zkg==,type:str]
  password: ENC[AES256_GCM,data:8Rfzw1r9Bvua6gaIQ/Zfg2uYgx6WS48V0UwkMmRMl44NJizsZueugJeurT8xY0vzgBcH7NMr/SZvHsCM/daGSZ4MJhYkcBAcEdz3S1lB89x9wzVt7QlE3w==,iv:1ZritPaytDbft8rReAKtmL7DVfpdnEtcqD/7/qRdgaY=,tag:ouMb2b8aLx5Fj1W+ppxoSA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb2lPdTVUcUFyMnNGbFB6
        akhRdGk4T0dTV1lvdjNpYndtSU52WmVXcmgwCm5jOFQ3K2d0NjRuenVTV2U3VUhi
        OTFUQjJkMGp1K1FWWFRxM1VybGhuSWMKLS0tIHFJelY5d0NHS1J0MzV4Wm5kOU1w
        aFVQSFQ5YU5xYnl3cHJrOS9MalNoZUEKAI7FuP6WTykzGBUNTUqcxxFE+MiZ+mPw
        txtYfONrRerFtiaYvVFQPwyEzEhALC0ElB6m/aijTEz0KJbbXtj2Wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T12:47:53Z"
  mac: ENC[AES256_GCM,data:SrMFa+F0++gEiq9EAZl7h6uQSs6jc+F/VHe9QRTx8AVDwLpCelVxucUDJJCUPBgb5CPioD5VPwE/Ct6zJytfnBnbG/Rh7QJ27OsPRqQeFh/lUvaDwOXI6wWshKrSeSC38NVvOEM5X2MWgtDoZzmOFcABZjzrsSB67MgvqwFbj2c=,iv:sdqfR3ZBnvRIUUGD1s7Mv7NZLBGmrkyiYDQZawl/CiU=,tag:eV4U/HMiVVERfiaIb1jXRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
