apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
stringData:
  username: ENC[AES256_GCM,data:qukbTBWrxSE=,iv:RWqy+NOrigoP4fbWvPYG3qQd86xEHORi8xFaYXV+bPc=,tag:L3qE089lZRvTEUAA1Rq3vw==,type:str]
  password: ENC[AES256_GCM,data:0He0gEp4Wz1VyY00LqwqEAhhIrzsd+Y58X1H5P5bA6G8vaQInp6IcYbTvYzrOcU1rttoSWo2n3vLQ3kxQwtWvWP6iFPITG8V2entbaVX0LbWcWtjeq7ORQ==,iv:px+8AGk/3IvSOdtwLfM98lr6HbxM7f6bvGCnt/CWu9M=,tag:fLl3cU189ltb70VUiHttSQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQlkyQm42RVR5KzdMR3hi
        WkhScWpnZ0Mzb0hGZSt5Z0djaStLdXRTbHpJCnVNaFA2NXJZQkoyY003SWxxYkVY
        ME5iQ3A3elRXLzFQSDczKzg2K2dRMFUKLS0tIGxzeVRHdXlMdXZROXlYQnRzVzhk
        TkttYlhWazFJN2xjUWNkdlAzcmxnSG8K7yOTNJwQ1u5LKvnE9AC8OcEAHdsImc3c
        rYmgz81nWobD12YOwsq+mM0diOyTnd9gCZek6+3tUc7lzrFZ27fyUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T10:10:02Z"
  mac: ENC[AES256_GCM,data:po50KvIP0nefJK06e7f40rRi8BwLJm66AEDFQlx1fdle0B7gUzKuu9SJs8L5tS+BrIrRIJjG9cAxUf5950BIgxtuKcJoKvoJp9l0nEs+3I/WnyBZXxNg2wOkIhxMUOpov+cQGo5a5VhUZtwWy50okQUKDdNBg5XBXTVWL6VwOME=,iv:TSUZK/whz5MXgvV7kneFYL9h5iyWDseP+yHF8Fm+TZM=,tag:dXs4GbiG+HLquPX766Sh4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
