---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: grafana-oauth-secret
    template:
      data:
        AUTH_CLIENT_SECRET: '{{ .AUTH_CLIENT_SECRET }}'

  dataFrom:
    - extract:
        key: grafana
