---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  uid: 659d3647-1d87-4fca-aaf7-dbf3647a2764
  datasource:
    type: prometheus
    name: prometheus
    editable: false
    access: proxy
    isDefault: true
    url: http://prometheus-operated.observability.svc.cluster.local:9090

  plugins:
    - name: grafana-clock-panel
      version: 'latest'

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  uid: f9c06a73-1fc7-4212-8751-424e2019b944
  datasource:
    type: alertmanager
    name: alertmanager
    editable: false
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://alertmanager-operated.observability.svc.cluster.local:9093

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  uid: 1db34a36-8be5-454d-8f10-bce05fc5f931
  datasource:
    type: victoriametrics-logs-datasource
    name: victoria-logs-server
    editable: false
    access: proxy
    url: http://victoria-logs-server.observability.svc.cluster.local:9428

  plugins:
    - name: victoriametrics-logs-datasource
      version: latest
