apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Zd7KMHqYQVE0ibwuIPGAYiu9MlNbKIjCjfcC8wi/G2Hsbka4Ix13ucCA+qv+0lH5tux4FdXKT5jyubY0i5gZqYzKAfF+tnfSdG/+w/YHFdCwTvRxyx0t2w==,iv:E1ItDIeHnCV2+zqnVU/yGnWdQm7QMHb0nsHT2dzslr0=,tag:iZmmGWIbgUYyrXTxzQTsnQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c3hBeVpCOW1MQjU2Zytn
        TjVmM0hVUVdjUEtEL0wrRTdnUWNoTjMzL3lrCjBMTDdEYTc5d1ArWW15R1dFc3F4
        bUg2Mm1yb0pRZUxTWTFrellqaGlKS0UKLS0tIFZYU0VHT3UvSmYvd1QvaTZXK3lm
        bzFOamMzMi9UaFZ5OXdid0VKNkRvN3MKT0XQMXM0e/uDewBxDt8neqWdTAJ6chTy
        OsMGmjXT8gQ+pjUqQ1BeQj+QKMd17539qb518jyhzn631NLhTnlWew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T22:58:27Z"
  mac: ENC[AES256_GCM,data:78Fu/hekemWBjbM+zwafjwPDDmLRIilJx0APmzVDlxGBn2USTOhxjQt2myy24xj3JuWOO6H4N1roQCkoEFGSprCfEMYfR3OPYeE2giJ3faAdKsLWToFRsU3PXjmyw7QhSAJ1FLeuIBV6WjHqF/eDW3mrHLQjZC/wCRoC1yPilEc=,iv:oriIpIpUy+Ni+wM3Dey8aS8t4zUkPyM6MzWtt8fVVFU=,tag:wW7ltjrPLLkx5+ihSqjgxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
