apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:ZYyW5qM=,iv:NJ+KtbgJOmZL6OY1ns73Pi0iCH7N2LcrajRtoSStVcs=,tag:/yhUVYTh20J/UT28KKC9Ng==,type:str]
  admin-password: ENC[AES256_GCM,data:PubzhAle02REIrsUD+UGYtktJhDuZ0OK5uycCQTYV+t7WrWWaEA9KkEAKW5UdrQzEX9qUFh8m8/JY3CbYdxiBbQ39qhBYb4oXL+jozmtW+FDmQa+nSKb2w==,iv:3F+ZEz9Ws8eH6zsk6m7BZNQgd/0z1lVBs+lUeywOLko=,tag:h1pyePtCniHGyu2uwAFGwA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScTJLbTJENzBla3g2cUFP
        d1JUa3pRS24xZklvUW8xbSsyNjRiNHJBU0ZvCkFsTjN2TWFHYVV4NW82MEpsMDNY
        RFU5Rm1aTnUzaHAvbUoyaWozQUR6UWMKLS0tIFgrUVlESCt6cUVaK2NiVHN6dFdz
        QkMwazhJRGRWazFnUE1BL21BMjVPZHcKAQRY1crYJZu93bUTxRLhEQ8G+HckozY5
        /iNiREQgzbUIbBPmElWOrQeSTq0zowRAWpt0900qPqFehuvcg1zytQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-03T21:53:19Z"
  mac: ENC[AES256_GCM,data:JoBA1uANtSKda/MGPEpvJ4ApAbvK1aCl79ndVBjMxBM1A271hVqezBo7rhlvQdfnCo0zOhvtE1HoKrUTs/tKaYAUVqrpOZhZ7CQrz1Gk6cCt10i2pPPdJt2u31AJsa9upVtMUJHe0YRgnQMSbMu/2UVjO+od7B3s77GwiMJHeYk=,iv:WwotQZjzkTNN/gaEtLO6lyWWDjMsQLb98G6HCN+qVfI=,tag:unqwXzdJGkYCm9Jw+waaDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
