apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:oEb+IfrMt/meFbqNbikn/5HFwz1dPhFHEQhsAJ5704v9YoDdmLTkLii/9CwIsunloxfOomvObpLu5sJ2K3eDQcwQyUHlcWKBv+wL5k2iSyHXBEkl0b6KWQ==,iv:MWKiyCLtApcbdhg998JwiEkC5DsinHPhaZTO+Ns61hA=,tag:AisMmTXJMWuKVALwXXn3hw==,type:str]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:QlXpPXM=,iv:E7dfLAhVrzZTgF1VC5WHy50sGhk412R3dubgR+Twbik=,tag:SCYbf81/b64ar88ZMVLEsQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0dVblFObmlUMldoaTBx
        OG5HVVRvQjlTcWZVa1dXaHY3aHAzQWxXdVFZCnptaEtGeUpGN25Td05MT1ZOTGdE
        WHc5cUxKVnBHc3J4RWVUWkF6bXJuK00KLS0tIDlUZWhJUWNLZDBSME5qY2kyRWto
        UWpLSkNFLzBrY2VlZVgxZGlBRk9wS28Ki3ka1R8OA32iBY/IMX97ztOsv9fUDLCh
        vlq+Cd0m4EKFHs3c3ujgPMk8OMxM68T6ABWNL4EIbDUIVkDUxErniA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T23:10:45Z"
  mac: ENC[AES256_GCM,data:yCC6FyM3nYU7q2zYkxzi2tjnRtGOam+Il/2RdEU9bs35oxnL1nycJ60CjJvG3DKZOVOb/43QNayRs3+Np8cvatlL4+X0k0ll0ByTJBj1Bn0cgG6KKOjnrCPiv+QK+urf0wMXI6SELL6ZbQu01fdgkty05GSZI9U4GT/B2foiaU0=,iv:QnIy56Ch7EGToWE3JMGUNQlRM4fdXzIlLdcvA5EXG2s=,tag:D/y+e3VsIBWA8azKGaZHTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
