apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  unpoller_api_key: ENC[AES256_GCM,data:NFF6D188cUZ/kTQO0Bvg14c9O3hE7Dy9KPECY2Xh3iY=,iv:rPM1rsRqra+LTENg+Pr3a+1m+TDZhjF7jrQRm2kbSA4=,tag:mc3KOYSLpFT/udtKxlV6Dw==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUpWSkFtQUFpajhWdmt3
        elZEMnNTQi9nZlJ1VjNGcm9SRko1U1hRL2tRCm82MmU4SFl6YzJuUXgvTDMveFI3
        bkh1VVdzblpIMVRIODV3ZDFqNk5hNmsKLS0tIFFsbXV0MUY2WTVpcEpVUDB4RWhD
        RlBqUXd6WUFZTXZGR2loRXpidzh3ZG8Kuan/WIWHcwWZnx1r9uZUW6tiqub5LHgR
        hMJkNVJMuPwwRgZEdOxONuSm0uDm/G4thixglhiqn+4LSNMFGfc7+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:28:31Z"
  mac: ENC[AES256_GCM,data:x5gmSdLCsd4Y+EireuKBZdbzZ7AKYhtwiM493ygbsp/cUJME97jhBMmy6mzkzicjJh9HQH6/5QUHI5nBtlG4Bl++aJjgzDUx0cIx3p3/lQO/KTK/WI0cy1djqUi7k6js8d0vYqcuARVkIlQvOUgMMFloeT9WWF/v9foOpQ1+P7Q=,iv:PLNeNk8ubfyhRJXTUj6/jNZH9sWYB59dg/4x7tjBJC8=,tag:4ZtD4OwtILJl6pTNzrtQpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
