apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  unpoller_api_key: ENC[AES256_GCM,data:LCrlv5bTrKrltRuawHggrrYNCrzI2pQ5y9iMA2D3v40=,iv:avHA/AAyy8BduqLsCR0bnoa0uilKUs/Gn78p/oQkjxY=,tag:6iDLZzSziJSvzslMmIGEbA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dmJMRm9hemdDRG5uYS9M
        SVA1UU95SUljU3pjR1BQY2NKZFZNNlZLSG1VCndjb3gwdUxtSjJJclp4ODlma3Vr
        STI0cGpiTkhDWnQxU1RtMXlvZW1mMkkKLS0tIFlib3hDcVBNcjhaTVBOVFZNNlVk
        MjdwS3VHSlZNbllMQUxZT2p1cFBtSGcKnE1nfGc4qklq0qdmbL5ZjEgdLr6/OFlt
        gp99l0MSi7VSAaEoVLRctDsQZybxRbfCg2ybggdim843RGcjfsvMxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-03T00:27:58Z"
  mac: ENC[AES256_GCM,data:i10ksoe9rDFBAO10FF+f6tMntqKXpJMm6dLy/uExDN338dqGQZsf1zCm20c6xwSNvoDMdhSPWoDdKqCHylAcYuV7cBN8ooi6LROk7as/kKXsM7dgwronRKo1XmVpL9O4l1l7BejbZZrG1rb1zGt4UKb7RuqgNGRVMa/BQDUJ4bM=,iv:jgsgi26DF35f8sQAMHveRKS5awEYBdq7SBBX6D8h+qk=,tag:2P3COZjLbQ8w7HvAmcREAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
