apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:P+Op07DqyGGP5gKLt5jEK0l8751i8I3ScNwGd+XHiC2BCGjEo8sNmw==,iv:1JEQBt9rgvWDmfadcyL3eq23YTqq89BF9fE/W02nwls=,tag:4Q47oVlY2YtPQ3XqNDdFBA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN0RSMTZobDY4SjRmSkZP
        dDV0amRXdlVGVVBSdXQ0MDV3eG1oL2RoZFNVCmgzYWxJNzFLYW9uNkFxdm5SWmtp
        aFI3V2lmaUJkMGpnbDZOWEpRNFZqc0EKLS0tIFRzUzlId0FGeVk5MFQ1Zmk3a21L
        Yy9EOEI3a2Y1cDV5ajRZclVPeG12aTgKN5UQ5V+GF0HTLlg75mepTNovGW0CDokH
        45jE5hpcbEzrqbAO32ksbnb/KiZ51L5tCbqAsibTHpfs0Esjf9CHTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T01:05:54Z"
  mac: ENC[AES256_GCM,data:JZVZD+unXmyKkrT7WlkXFTwnE0fvJCOWEa8pu7AhC9INk1wTvzURa/BrAhR6eK2VNY5Iuuct0BDmW64+rmNEfc7Uwj11azpuNYWXOicTrgcrbOtwfcAuH8rzA4OadGUmJXfr3+jekHPw/2kD/rywpr1Z/RVYOQxFgWjvw35PLew=,iv:C9GQqj+lREMsalluWGTqgBpj+SciVQIfPrH7+VK2MOA=,tag:hOyA/jVOw5gZ6gHJMl8EYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
