---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-auto-languages
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: plex-auto-languages-secret
    template:
      data:
        PLEX_TOKEN: '{{ .PLEX_TOKEN }}'

  dataFrom:
    - extract:
        key: plex
