---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-auto-languages
  namespace: media
spec:
  dependsOn:
    - name: plex

  prune: true
  interval: 1h
  path: cluster/apps/media/plex-auto-languages
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
