apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:ruBUKwJMi6vbdSzz4Brs3+1ss0VPeLxxAGYGostK,iv:/U3WLe3RvnM/x3CVuNEw4sDH2FMIey2RNjGPvl1ljmk=,tag:GeGgkfKnsWLKufks9rODnw==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:oBpV7UQcU+MgxAgKX/RkLRCqdKWx5sg0BcHujIHR,iv:ays3cWlA6HT+RcLUfS9v5mTlGX9r1kZv2CIqbcrjbIM=,tag:zDnzqUdjDTsCrCkJpb9DfA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWFhaVFp0SkFBTTNvSy9O
        RDVaOU0rZ2xnWmdMaktYRGNMby93cHM3YVRvCjVkanZDNjRrRC96RjRYWjVSdkNv
        dElmRHNFU0h1bzR2T3VNRFIvZUZ2aFUKLS0tIEtiN1lFTzJhQ3RYajJuL1pMZXNk
        RGFvYUJRd0U3UUVRYXpEZHBVYVlkQjQKO+yKjJCVlUkFpmebM9zfhrGFTl3AgSeK
        D6RNNUUKuq9wWTtds2L6mBS8eBht5VeYpgLIQGcPaGTC8xPXaZbXPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-11T18:56:41Z"
  mac: ENC[AES256_GCM,data:kSzsXd5kxUc45m5+Y5e+h0CHI/9fn+4BDuld+IFygQvWeh1AF742JbSbd9Y7jiWblLLiz7dhg5/B/w50+qx/gWenGSkdhD7x+1JnB6+RLNUNO2klwKaZNFXGSv3N64Y5VEpLAOHlv+UqbY0UgcwRd+oBNEc778gu5hSUSyo/gYU=,iv:fV5RrMNlhmpBWM4hKXS9FcUGvWRoQwCzvbCHJ2YAuV0=,tag:nPsDPNn/daApvqxHQu8DTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
