apiVersion: v1
kind: Secret
metadata:
  name: pushover-secret
stringData:
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:21zB53DnPkHf4FBYB6V47AHe7jFusjpabq2UIWMc,iv:NQvDI39gYGuYUcHxI9T5gBQn0f+TgecjDEJnkXEyQBY=,tag:+JfqZD/WFxMz6CEY8Rd1TA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:QSAoL/q4I4MfzmckQRk/8KI9gYXbMTZkzhMcbwvo,iv:L3aShT/DOUbvgl/8IirkM7A4UaAujq0A4JO9t8DDNGc=,tag:sTIzirfB+6j/l8W4lNiCWQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0Fjb3ByWTdudzVkZlNT
        MDRHbFFkVktxZTJnRWd5L1JvZjJYdkQ2M1RBCjlrZU1rajVUbHNTTGNOQlBneVhv
        a3lXcXBScTBUeWsrNXNXdENMc21qYUEKLS0tIGFDcmRrT1gvMHBUVkE4UXlGdjFp
        d3ZMWjBvcFBlbFlJZzZHUnNWa0VDNEkKlpkd4nQCaQFCxyuQQ67aUVPk00XeuJ6A
        OFpEBK2djJJO6H4Io2d+0aSV/r8HOwDNcaX3xoWP1k4sV6LZdhwBNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T15:58:35Z"
  mac: ENC[AES256_GCM,data:gnRLsGFdae/HH+K9v9mDKkXW4yrD/wmMqW51ftTHwUlE3sQn1UNcKsai4MVjl88Z3PeB3m1bxvfksFaC5ptnan4pbZCwDft1dPBylROVp+cS2LXjYSEvd66D7N6dAPPjwl9U4L8eUqeuCAjV1bTD6uTxcfnXd5bWP7SYb+icT/Q=,iv:gTGf8sOcvHf5Vin2kz52ePMgaM+SL2r3PxmIDTP78vw=,tag:wWRmtyvg1aBwaA796H+DVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
