---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: longhorn-backup
    template:
      data:
        AWS_ENDPOINTS: http://nas.minio-system.svc.cluster.local:9000
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
        VIRTUAL_HOSTED_STYLE: 'false'


  dataFrom:
    - extract:
        key: longhorn-backup
