apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup
stringData:
  AWS_ENDPOINTS: ENC[AES256_GCM,data:wCuGkjlx3oRe2N9Tslp+hVyia1V+sbefpwnQV9B38fftTqdka1i1,iv:YQv4cQGWebNt5zxSejRHFWMFjtW+MMbZZ3YT1YxJ1t0=,tag:jUWp+4vb0Etu4MWXbFMT/w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DQuIXwjSQPyNF3fil6+9juqX5Ddm,iv:ekgjAtdtV5azyQNnjgiw7987y1GmNEh9TCE3blNABY8=,tag:thp9cYsuHw81x+VdlSXc+w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PkM1suR3S5y3lA+JK7zepJjtGKaJ984Jj+h+YG2IfL3qU9A39wNJ8RphvzoWt++EJJJ2Jk1ByhfzN8WwWOCn7DxQeaaCEkaErlvgV0WfLu4I7tBOInURXQ==,iv:wcfF8QrYrTyvkQTIDAo1ZQvMZVreRunpoqVk0wcLThM=,tag:1z21yFYn7HPVecXsutVNBA==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:q2UQZ5k=,iv:G2+jxsGMDed61P9yk6SYDLhbWFu/wPQiEdc5AQhUIpE=,tag:+t7zWgF3qin9zB3heuIJzA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2alJUS2tZb2dHMTdRMVRo
        K2EwMFYvbFhrZkRFaWVCenl3WERZVDkzb2tjCms0K3pjbFVTT3ZWbE4vZUI2QlF0
        QzRrd2NGSVdhaDVLekhzbUNrUHp4VFkKLS0tIElBdWNtVWs4NjJYUWtZUEdOOVdE
        TTNSVS9xMWtIcVIvbVZ2TUYwTmxqS3MKLNN45QmzGCxRg/hiNcabcZ+HrStmExRm
        3zuCesONzu25CdR0JMjb1JQ8XeZVKLDf+CF03bUQkypdeBqSE+ZpgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T22:34:29Z"
  mac: ENC[AES256_GCM,data:exQAxpcglDhgAKad0ZCAUONgbthQb0Wz/BB+qeqKUWbjf3YFEExsM40Js1kYWd2Cq+/5vb8i3Nh6rerYxoRNPoAFTtRnVNa8nKrjzJFZ+qKJFcpg+6gavUFMsO2/iFCDFThQK+9go3q/VWKMOEFkDasR9SYeelq9MltO+QcsqMw=,iv:F2Zj2qSkqECQ8hpbcl2/rvS0mrQo/QSSBzqQcGS+2BY=,tag:1WpXWsHFl8kZ5y0vA+A4/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
