apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup
stringData:
  AWS_ENDPOINTS: ENC[AES256_GCM,data:03kcZUJiQvx8HW6ILJBT2sQe3jkmqexCGwrS0G+JUWcMkSzcqoxGsMkCsmJv8Q==,iv:HNe9mo7MEpGNTETUUmaj29SYX09LUSWogoNPGLsBtEc=,tag:XZ14qxMuCG4STlpzlgVo2A==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7SKw44fIG9lnLrAeBSuhXDWYl6ji,iv:dl/4la7FLLp45yYi3ATBfHFCPKuVLfe/HVnTR6LT5wU=,tag:IQf/TMPqnUFFDyNkCUjKFQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bXtn01x2mrZSFQWA1MLwFz2i1RadPFpgXA00lzS7VZYi3yld6uXoMwATCePcGJEyuNRm7G/nKJYEIVfLL5lvQ0j3OrUCYaygsxIRGJCdTqO4xs2kiwymOQ==,iv:JnIJU4v+7PIVVMysvYHv8IbPF2nVaePDdcJ/JWaiO88=,tag:SRO9zNa2z22DdP6sBDSPCw==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:anxLvKo=,iv:eZzuk0/d5L4oZXwexa22s4I4NU5rJCNwZdpnv10d/F0=,tag:/XBzho3hBtBUylhia91kjQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcVBXWjUyM2hua3RCT3ZY
        V3d0WjU4b2VZdjdock5URGIwNGtXWDF1RjBFCmdhdGQ2Z1JuQ3dIem5lVFhaT1Fr
        dlhkMitJV3RBUzVxblBwOVByMlVyV0kKLS0tIGJwTmFWYWozSnFQU2lnUFJyblZX
        Um5aRXhZUDVkZ1hVc256OSsvMzdCOHcKqz/L41J7HfHsAimFaascoOGFUJR1ivju
        scJ0Rg9htvmW6/smo4X08saKc9dMBDYwaY8dmTK1inYOgdTA4xkbCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-26T02:53:05Z"
  mac: ENC[AES256_GCM,data:d4AQ4YYIURstT3mCTH0TImqsKKk57ewgVlmJQLrfeDgEmHTKYy+EzsEI2puPy72WsZXKh9PL2ytOHwag5DVpnuSJatmL8ntLPkPZ1lCSzyYl7kFAOw545+cnfWRMKBHO78kovpchTa+/9ixmoW6ZRQX3EJlabiIzIrRu+Hzy264=,iv:eVWZS1x9Lfy6gB1/K1EaaQlzKM7APQ+I8v6Pp85Ivko=,tag:MuAqlP+PY2nSN4uwN7kDaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
