---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    kyverno.io/ignore: 'true'

spec:
  instances: 1
  enablePDB: false # TODO: Remove when more than 1 node.

  enableSuperuserAccess: false

  resources:
    requests:
      memory: "2Gi"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik

      dataChecksums: true

      secret:
        name: postgres-authentik-secret

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "800"
      max_slot_wal_keep_size: 10GB
      shared_buffers: "512MB"
