apiVersion: v1
kind: Secret
metadata:
  name: postgres-authentik-secret
stringData:
  username: ENC[AES256_GCM,data:4AP6AyodsAVk,iv:ZQ1g5arrLUeo/BTnDk4+it2gQFEGonyXkGHTV1/i4Ro=,tag:okKbjMVehloGZMXaVMK/Rg==,type:str]
  password: ENC[AES256_GCM,data:k9iPEC3kPSpLBjbuGrnopICLqFvNwaPEmozFNKxP5HjX4qFVYWJU9ayqepvVJoBPHiUvz2jX0RPKQcc/z60+LFENZo3IJuAF00rsSanUchBkSP7RSksccg==,iv:uBzkTxHLHpzjD45jC151NzVuwot308doWKD81RnHtdw=,tag:h5c9IQPoEr99H9qiWICYjg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZk1pdmVMak90SFFVSytP
        K3NSeW1VZkJNcnhXMkI4RjI5clEvbCtxT0I4CkRQTjBDRjNRSHdOeFJjUzMyWUYw
        eGtBcHo2blpkQ3hmdzU5anJJamJxeE0KLS0tICtaSkNHV1BCTVltc0xwQmxYaDVl
        cS8vUlhaK25sd2VXUStiK3dPbjVQTUkKpfklN5U0GoHXe6VluRenk+NLkjMzu9l+
        MHAdT994tkp7JJ2IJL4u4sCSSS0KLSik7d7jgN8X+orQHzRcTMfzYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T00:14:44Z"
  mac: ENC[AES256_GCM,data:qSqfRtATmFn2ZEXr7xji5LJ4iUKGySKsOCrEeWM0iEr0p0gHbpaTcIWmwyvNRuc+GSfHNxi+lCRJwgZVuze6/88QZ13ar6tc3RToGWi8y+pGIZ0C+3eV0ENDqOCa8yc6AHE1wJCjuyTbtbyXslAV7Z+jVf1dCV78j51E7QSbcG8=,iv:gVU49fEbBY4+Kg5uH5laVSPxm7hdLEdA4FW30qifzbc=,tag:CPMd4x6Z6DejgJmRNHlfPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
