---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: radarr4k-secret
    template:
      data:
        RADARR__AUTH__APIKEY: '{{ .RADARR4K_API_KEY }}'

  dataFrom:
    - extract:
        key: radarr
