---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr4k
  namespace: media
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

    - name: prowlarr

  postBuild:
    substitute:
      APP: *app
      PVC_NAME: *app
      VOLSYNC_CAPACITY: 10Gi

  prune: true
  interval: 1h
  path: cluster/apps/media/arr/radarr4k
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
