---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998

      organizationID: e8a59421-3eea-4f00-9dbb-afcd016934e3
      projectID: 60b0c5cf-b4f6-4e35-a547-b3bf0141a3e5

      auth:
        secretRef:
          credentials:
            key: token
            name: bws-access-token
            namespace: &namespace external-secrets

      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: *namespace
        key: ca.crt
