apiVersion: v1
kind: Secret
metadata:
  name: bws-access-token
stringData:
  token: ENC[AES256_GCM,data:0byjhKIKDAHRrMye479wk94XxEaix9/SO3nkorX0PiR7NzCd9l1vMxxf/sZ14+8jP8+TA0xjiaU8faE5M56XLLSzKTHbno/KQvt9Qr1pbnE8PaozUHWka6/1iD3Xkw==,iv:XPBp+LCBlR3jRYWyYXlLfvQMk7M1vUfJrmizkt0wN+Q=,tag:Lc84ShhBrm6iq3eW8iMPbA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR3pYRk50UTROSnM2b2lW
        Z1ZIcTNUWmczdzk0dUZScWVieWhFd2EwcmxFClg2NWtWQXhyRlhvSVF2MlAvVXBt
        ZU5zeGFFZ1llQ1ZwYTU5MklQYlNiM2cKLS0tIEdCK0pkbnlVeWF6ZDdsM1k4c3Yy
        QTkrNk14VnFVWG51SklTSnJQY0tpUGMK3YpfnpML+sbCV+JeIjBPCcFtOs5wqZwm
        c+2dWEqblE7vKd0pOjcxM4rxXPMtlZsYksSqfD0gbj6gdFaXpM5tOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T20:53:27Z"
  mac: ENC[AES256_GCM,data:MC53+bdGjv3iTaw4SNpY3cFIY1ZyfyzL7x9INu8c4Jpc4z2HxVvDk5zX16qEAUCUKI7eLC/tsf09/DaEEucNyKN0ueL5eXOdssswc5YPgmIUaMl/p0brG4mxmZZGYyR0GjqvQjVVEQTNm0E+LLm7tZUwqhkLHPJThghHJDPRvcg=,iv:jR8Vi5Whb3Awi022VJ73xOI50Fw3EUuAqE0fYYdHBoE=,tag:W6xgU2H+VzlswqcwoUUz+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
