---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-gateway
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app



  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true

  targetNamespace: *namespace
  path: cluster/infra/kube-system/cilium-gateway
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
