---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitwarden-sdk-server
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.4.0
  url: oci://ghcr.io/external-secrets/charts/bitwarden-sdk-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-sdk-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitwarden-sdk-server

  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    replicaCount: 1

    image:
      tls:
        enabled: false # TODO: Use tls certificates!

    securityContext:
      capabilities: { drop: [ 'ALL' ] }
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
