---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-recipes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: tandoor-recipes-secret
    template:
      data:
        SECRET_KEY: '{{ .SECRET_KEY }}'
        S3_ACCESS_KEY: '{{ .S3_ACCESS_KEY }}'
        S3_SECRET_ACCESS_KEY: '{{ .S3_SECRET_ACCESS_KEY }}'
        AUTH_LDAP_BIND_PASSWORD: '{{ .AUTH_LDAP_BIND_PASSWORD }}'
        FDC_API_KEY: '{{ .FDC_API_KEY }}'
  dataFrom:
    - extract:
        key: tandoor-recipes
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-recipes-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: tandoor-recipes-oauth-secret
    template:
      data:
        secret: '{{ .OAUTH_SECRET }}'
  dataFrom:
    - extract:
        key: tandoor-recipes
