---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tandoor-recipes
  namespace: tandoor-recipes
spec:
  postBuild:
    substitute:
      APP: *app

  prune: true
  interval: 1h
  path: cluster/apps/self-hosted/tandoor-recipes/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
