---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: unifi-dns-secret
    template:
      data:
        UNIFI_API_KEY: '{{ .UNIFI_API_KEY }}'

  dataFrom:
    - extract:
        key: unifi
