apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:7HRTTRKk++g4Ew+Xw8dFVFrIOBqS8SgxZx8ORjUqukI=,iv:xcem1qOsMoh/YwnH1/xrGd6KowW/xGIErWZnaa8tHOQ=,tag:WVyKlP2xcyBlE6VIktevFw==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbjBhb2tkR0QrNFhweTZZ
        cXlFUnNSSjJqckZ3a0Y1ZzFKWjg4dEZzS1EwCmh5VmFDQ05lbFZOd1FsU0E4cStX
        Vmh2ZlNmcEpWdE8ydGpnbURaalFYQ0EKLS0tIEZMU0RGVWs3dm1zSTdqTkNzZjV1
        VmY5MEQ4UEZHbElBc2k2NmZPT2ErSjgKMr0YEx+rjQxmFVJiKPHfrlxYtBSIVWpy
        BdV0pbb/82lBOyQ+5Odtz+FX8nW0Q0k+HlDIy60ZShS1Fx3/pGzR9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-17T17:48:30Z"
  mac: ENC[AES256_GCM,data:9gEEfa74sAw/+UiWpWALgNF+StPKDHnT/uDTQbPzkUobLWgO8huD8clbJ8pqBcs+6d81KCkpIW29PFicpfavUdEyX8d8X3VArOKQ3oJ9CqQI1TMM3Rbjm2RC19lDZ7CRcLToKQsBlzKUDA4uDly9uQIyACete7gRcz4O7xc2PhA=,iv:hovFYfxUweFCTRiyxMfEdSQalYwLT9lytP/O+5Fiy6U=,tag:vqc7SZYRYT3OcljIC8yU1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
