apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:EgrEMEYjRpyKMRtnkqBdFDa0vELB1KL53fMSsVWgsNY=,iv:FcuaOunHfuLzK0Fj8g7FCELFNFAnf5sBAX+00bgdphI=,tag:TGDH0pTxbS80/pDD/oj2TQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WnJoeFNrbFNTWVE0dElS
        QnBMMENHWFdSczFkZHh3RVJ6Z0hvNDFYMFVNCjdRdlhQT09neW9YUDUwRCtoUWZZ
        SjRlZ1BQbThVckFOM0lRN2FLbHVpRDgKLS0tIERsS1dPUXV3M2ZuckJaQ2xFTlJp
        a1p0VjBhb1VhS1hVd3MrN3RBQkxaQ0kKharQKIODvXFcUVlGyk/ylunw0rRyzSWC
        kg8BXTOxfApACHA+9Wl+UMxm08HCccTyulYnZNDx8g4gDKSG5G1Vqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-03T00:26:48Z"
  mac: ENC[AES256_GCM,data:cNN4lpq4UPTcKVZxnqHHz/Bn4qJX7IWCqmZv+8rm+64PicpWcNxjwEs3vii4xUPvTdp5/zVCCTubi1Wmz7jl/032EaY1eI3EoJhsaDwBKjdeSXv0z+N/u/lN7uKz5Sv+1h7oulJpfaUIEYXeLPANECkiYaO6reNneKqZ+qh8oa0=,iv:h9Fa7FytTMcRWqULKDTxy/N9juloEl9sDPmSJLDpk84=,tag:KZpd5mAPjxw9HcE/VvFy5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
