---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: kube-system # Required for Renovate lookups
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: kube-system

  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    enableNodeFeatureApi: true
    nodeFeatureRule:
      createCRD: true

    master:
      replicaCount: 1

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ 'ALL' ]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

      resources:
        requests:
          cpu: 21m
          memory: 51Mi
        limits:
          memory: 256Mi

    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ 'ALL' ]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

      resources:
        requests:
          cpu: 5m
          memory: 48Mi

      config:
        core:
          labelSources: [ 'pci', 'system', 'usb' ]

    prometheus:
      enable: true
