---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.18.1
  url: oci://registry.k8s.io/nfd/charts/node-feature-discovery
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery

  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    enableNodeFeatureApi: true
    nodeFeatureRule:
      createCRD: true

    master:
      replicaCount: 1

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ 'ALL' ]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

      resources:
        requests:
          cpu: 21m
          memory: 51Mi
        limits:
          memory: 256Mi

    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ 'ALL' ]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

      resources:
        requests:
          cpu: 5m
          memory: 48Mi

      config:
        core:
          labelSources: [ 'pci', 'system', 'usb' ]

    prometheus:
      enable: true
