apiVersion: v1
kind: Secret
metadata:
  name: radarr-4k-secret
stringData:
  api_key: ENC[AES256_GCM,data:nHDuiKE2q20u/eWiJa298KtHIWkXmdLkqP3DQdQnaVMe71uGQy3MFA==,iv:p+VV7J5Ur7xgFvTF+iSoKQTpX0b9uK1tRa+urhanOrs=,tag:yFRFz2a7MWpNmtxDB2Uw4A==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SjltcTA0bDRHajk0bXBx
        SHE1eFdUdys3Y2dMQXJJdmZXdkd3TXRCdGlBCmJ0SGZjanJFSmEvdStnamxCb1FD
        SW5YbnlVNVB4aElYY1RQeGdFTW1XV3cKLS0tIEdmK3B4NS9hZENLQ2dzNWdDdjF2
        bGg1YXd4RTZMYStvOHZ0QTNFSEUrbVkKZCazUHUpkSNMUU/5pLD1ChIOkhiHPEzP
        h7LF13EUcBXcmrL8TB/vt6UmdIOIQa4iGRGGEY6ANql/A3GBo9uopg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T01:06:10Z"
  mac: ENC[AES256_GCM,data:uqbP/eQsMHhVAPebIC4oqtN9PgglGu/5s9DgmJn94t1ZGUwVLxmCf3Qk9PY5/l7wqsP7WPqS/sPjo1I3O6d4w/Eqf8N0DXVo3ZxX9M2A5bE9hj0BBoiTQhnKRc4DsCfenMyJE+/+aETNMs7iwtTaGct62fkAGbQbyFhEPPSBVd4=,iv:vt6AH/CJw+FylEcBB+OjgiRV+csSHCpkRXVsqhPPlwA=,tag:gh95QF2t1cVVlI7eh5hOlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
