---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: main-proxy-config
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1

      envoyService:
        name: envoy-gateway-main
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: metrics
                  port: 19001
                  targetPort: 19001
                  protocol: TCP
