---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: gitlab-runner-s3-secret
    template:
      data:
        accesskey: '{{ .CACHE_S3_ACCESS_KEY }}'
        secretkey: '{{ .CACHE_S3_SECRET_KEY }}'

  dataFrom:
    - extract:
        key: gitlab-minerva-runner
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: gitlab-runner-secret
    template:
      data:
        runner-registration-token: ''
        runner-token: '{{ .runner_secret }}'

  dataFrom:
    - extract:
        key: gitlab-minerva-runner
