---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../components/namespace
resources:
  - postgres/ks.yaml
  - timescaledb/ks.yaml
  - ext-postgres-operator/ks.yaml
