---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - postgres/ks.yaml
  - ext-postgres-operator/ks.yaml

  - dragonfly/ks.yaml

  #- timescaledb/ks.yaml
  #- ext-postgres-timescaledb/ks.yaml
