---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dcgm-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.5.2
  url: oci://ghcr.io/home-operations/charts-mirror/dcgm-exporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dcgm-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dcgm-exporter

  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    extraEnv:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all

    nodeSelector:
      nvidia.feature.node.kubernetes.io/gpu: 'true'
    runtimeClassName: nvidia

    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SYS_ADMIN

    resources:
      limits:
        nvidia.com/gpu: 1

    serviceMonitor:
      interval: 15s
      honorLabels: true
