---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
components:
  - ../../../components/namespace
  - ../../../components/flux/sops
  - ../../../components/flux/substituteFrom
  - ../../../components/repos/app-template
resources:
  - cnpg-barman-cloud/git-repository.yaml

  - operator/ks.yaml
  - cnpg-barman-cloud/ks.yaml

  - cloudnative-pg/ks.yaml
