---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: postgres-s3-secret
    template:
      data:
        ACCESS_KEY_ID: '{{ .ACCESS_KEY_ID }}'
        ACCESS_SECRET_KEY: '{{ .ACCESS_SECRET_KEY }}'

  dataFrom:
    - extract:
        key: cloudnative-pg
