apiVersion: v1
kind: Secret
metadata:
  name: postgres-s3-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GqXUEp67i+mdXxQ60pZpNcXM,iv:YJRYTrdPOrSMfTOyMDLjIexnOrenuL1TmTfoKMD3qnE=,tag:dq/SfEebRnMjuC5XmBc8Pg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:oW1TGE7yc46AhJp8m6o7qXInuOovZzFmdRt/ryCVdhGGlNkWWBDFyMWEK3S0hJt7s59ppMOvGyjcZ+jcscgYJW9Aa6qbQaC0o74jSHKwI2PDRxOpGx19IA==,iv:koMyRM5FAlHni9IovXHow5foBwZL6OqqA+ps6X1Lo8o=,tag:NU0ddT1meszDjsP9WysWtQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM1Q5YVp3ZExkdUdjTG5n
        ckFmR3BpOGw0NnVueVJRSUkzR0xhUmVxOWpVCmJ3cnlGTUltM2pDNFpTZDlxSStv
        SjgyM1dyanNjQitiQjZSYkFIUFprUFUKLS0tIGY0OWVvU0dlOXowVGtvSldZSzlC
        ZmZha3MvOWE4dWV2cDBjQTVSYklqQmMKbyARY9c5CetrPi0noPlexiucRuMrRe5D
        YztXl//8nnBnz3QY9mTA6t4M8DKJ4/olefnotdJc0zNzw2j7Ol4Fxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T10:09:58Z"
  mac: ENC[AES256_GCM,data:J2PdANzmWpL9pNcUaj5VZlNtX8Wk4Gq8CunjV7qzuVqpz6ZugBAYb53vWSCEJf+kbm/sMCRe1y98eSIrjcwNlhbl+FzFY0stioLjMWrWvJhi3NC8Lo5Nv53kVtX8jElhBitGMxgLuEzV+CtOyDpLGdv7UlrnRcWrHnZLs5LnqUc=,iv:AT2aqtQkS65TuUQzTStQn5gUPwxjnusd4slNb0vwX8g=,tag:ZNqpfVgN+CmwyOUXGV5aJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
