---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dragonfly-operator
  namespace: &namespace dragonfly-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true
  wait: true

  targetNamespace: *namespace
  path: cluster/infra/operator/dragonfly/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
