---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-policy
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1

  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1

  # Not supported yet: https://github.com/envoyproxy/gateway/pull/5671
  #http3: {}

  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
