---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates.yaml

  - configuration.yaml
  - gateway.yaml

  - policy.yaml
  - patch-policy.yaml
  - redirect-to-https.yaml
