---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy-all
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway

  compressor:
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
    - type: Zstd
      zstd: {}

  tcpKeepalive: { }

  timeout:
    http:
      requestTimeout: 0s

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-all
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway

  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.42.0.0/16
        - fdd5:aa8:9535:42::/108

  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1

  http2:
    onInvalidMessage: TerminateStream

  http3: { }

  tcpKeepalive: { }
