---
title: Homelab
# background:
#   image: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/assets/101518784_p0.jpg
#   opacity: 20
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
theme: light
#color: slate
headerStyle: clean
statusStyle: dot
useEqualHeights: false
fiveColumns: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

layout:
  Calendar:
    style: column
    icon: mdi-calendar
    initiallyCollapsed: false

  Dev:
    style: row
    columns: 4

  Self-Hosted:
    style: row
    columns: 4

  Media:
    style: row
    columns: 4

  Observability:
    style: row
    columns: 4
