---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ext-postgres-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.1.0
  url: oci://ghcr.io/home-operations/charts-mirror/ext-postgres-operator
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: '^https://token.actions.githubusercontent.com$'
        subject: '^https://github.com/home-operations/charts-mirror.*$'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-postgres-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: ext-postgres-operator
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: postgres-superuser
      valuesKey: username
      targetPath: postgres.user
    - kind: Secret
      name: postgres-superuser
      valuesKey: password
      targetPath: postgres.password

  values:
    podAnnotations:
      reloader.stakater.com/auto: 'true'

    postgres:
      host: postgres-rw.database.svc.cluster.local
      default_database: 'postgres'

    resources:
      requests:
        cpu: 5m
        memory: 32M
