---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: gatus-secret
    template:
      data:
        PUSHOVER_TOKEN: '{{ .GATUS_PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'

  dataFrom:
    - extract:
        key: pushover
