---
version: "3"

vars:
  KUBERNETES_RESOURCES_DIR: "{{.ROOT_DIR}}/.taskfiles/debug/resources"

tasks:
  netshoot:
    desc: Create a netshoot container for a cluster
    summary: |
      Args:
        ns: Namespace (default: default)
    interactive: true
    cmd: |
      kubectl run -n {{.ns}} netshoot --rm -i --tty --image ghcr.io/nicolaka/netshoot:latest {{.CLI_ARGS}}
    vars:
      ns: '{{.ns | default "default"}}'

  privileged:
    desc: Run a privileged pod
    cmd: |
      echo "Using envsubst: $(which envsubst)"
      kubectl run privileged-{{.node}} -i --rm --image=null \
        --overrides="$(yq {{.KUBERNETES_RESOURCES_DIR}}/privileged-pod.tmpl.yaml -o=json | envsubst)"
    env:
      node: "{{.node}}"
    preconditions:
      - which envsubst
      - test -f {{.KUBERNETES_RESOURCES_DIR}}/privileged-pod.tmpl.yaml

  ceph:
    cmd: |
      kubectl exec -i -t -n rook-ceph deploy/rook-ceph-tools -- bash

  external-secrets:refresh:
    cmd: |
      kubectl get externalsecrets --no-headers -A | while read -r ns name _; do \
        kubectl -n "$ns" annotate externalsecrets "$name" \
          force-sync="$(date +%s)" --overwrite; \
      done
    preconditions:
      - which kubectl

  reset:talos-upgrade:
    desc: Reset failed Talos upgrade
    cmd: kubectl annotate talosupgrade talos tuppr.home-operations.com/reset="$(date)"

  reset:kubernetes-upgrade:
    desc: Reset failed Kubernetes upgrade
    cmd: kubectl annotate kubernetesupgrade kubernetes tuppr.home-operations.com/reset
