---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/authelia/master/docs/static/schemas/v4.39/json-schema/configuration.json
totp:
  disable: false
  issuer: auth.talos.${DOMAIN_NAME}

webauthn:
  disable: true

duo_api:
  disable: true

log:
  level: debug
  # format: json

server:
  buffers:
    read: 16384
    write: 16384

  endpoints:
    authz:
      ext-authz:
        implementation: 'ExtAuthz'

storage:
  encryption_key: '{{ .STORAGE_ENCRYPTION_KEY }}'

notifier:
  disable_startup_check: true
  smtp:
    address: 'smtp://mailpit.kube-system.svc.cluster.local:1025'

    sender: 'Authelia <authelia@talos.${DOMAIN_NAME}>'
    disable_require_tls: true

authentication_backend:
  refresh_interval: 1m
  password_reset:
    disable: true

  ldap:
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))

    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter

    user: uid=search,ou=people,dc=home,dc=arpa
    password: '{{ .LDAP_PASSWORD }}'

    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

session:
  secret: '{{ .SESSION_SECRET }}'
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: authelia-talos
      domain: talos.${DOMAIN_NAME}
      authelia_url: https://auth.talos.${DOMAIN_NAME}
      default_redirection_url: https://talos.${DOMAIN_NAME}

identity_validation:
  reset_password:
    jwt_secret: '{{ .RESET_PASSWORD_JWT }}'

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: [ '192.168.0.0/16' ]

  rules:
    - domain:
        - 'auth.talos.${DOMAIN_NAME}'
      policy: bypass

    # Webhook protected by secret
    - domain:
        - 'flux-webhook.talos.${DOMAIN_NAME}'
      policy: bypass

    - domain:
        - 'rook.talos.${DOMAIN_NAME}'
        - 'grafana.talos.${DOMAIN_NAME}'
      policy: two_factor

    - domain:
        - '*.talos.${DOMAIN_NAME}'
      policy: deny

identity_providers:
  oidc:
    hmac_secret: '{{ .OIDC_HMAC_SECRET }}'

    jwks:
      - # noinspection YAMLSchemaValidation
        key: |
          {{- .OIDC_JWKS_0_KEY | nindent 10 }}

    cors:
      endpoints: [ userinfo, authorization, token, revocation, introspection ]
      allowed_origins_from_client_redirect_uris: true

    claims_policies:
      default:
        id_token: [ 'groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name' ]

    clients:
      - client_id: immich
        client_name: Immich
        client_secret: '{{ .OIDC_CLIENT_IMMICH }}'
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - 'https://photos.${DOMAIN_NAME}/auth/login'
          - 'https://photos.${DOMAIN_NAME}/user-settings'
          - 'app.immich:///oauth-callback'
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post
