---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/authelia/master/docs/static/schemas/v4.39/json-schema/configuration.json
access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: [ '192.168.0.0/16' ]

  rules:
    - domain:
        - 'auth.${DOMAIN_NAME}'
      policy: bypass

    # Webhook protected by secret
    - domain:
        - 'flux-webhook.${DOMAIN_NAME}'
      policy: bypass

    # Public media ingresses
    - domain:
        - 'plex.${DOMAIN_NAME}'
        - 'tautulli.${DOMAIN_NAME}'
        - 'seer.${DOMAIN_NAME}'
      policy: bypass

    - domain:
        - '*.${DOMAIN_NAME}'
      policy: two_factor
      subject:
        - 'group:cluster-admins'

    - domain:
        - '*.${DOMAIN_NAME}'
      policy: deny
