---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  type: ExternalName
  externalName: tautulli.svc.alexsaphir.com
  ports:
    - name: http
      port: &port 80
      protocol: TCP
      targetPort: *port
