---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name garage-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 5m
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: garage-config-tpl
            items:
              - key: garage.toml
                templateAs: Values

  dataFrom:
    - extract:
        key: garage
