apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  DOMAIN_NAME: ENC[AES256_GCM,data:TnlYFteWco+3wZb+Jak=,iv:r9Vm2AEsuX3unDHA62RjIBI+6y+1OD9bt0s1lPR1+Hw=,tag:LdJGO/RefCnzrnRlGvAyig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRmNadGdJdlJ4WUFXWjVF
        RUxVSE84QllPVTlXTndJR1JMTEJDTDhQTGdVCmc2eHF0NXNwblErT1BtTUtqS3k3
        TlB1dDVkYXdOcEZUU2x3cG5tQXpQam8KLS0tIHhLN3YwYmZybFJ1M3IwMFpnODdq
        V2x6ZUtCMmE2ejhRTDBNVXVpUnJlcW8KYBiCmLCFDJe8jHclfMPqXs0m5xjvSPYy
        KZCCKgC435Pad6dgCiPH3OtF12rFfYmDGJipFDY0Azg5DyqSiUlK1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T01:52:40Z"
  mac: ENC[AES256_GCM,data:KqnRkgvOVxoksNAT7qL4V9vmxWSEU5JLDqCg7NJ9scHQVjqLfB1XlXAilfvJNytxgt7tHKFUaaZybCFFfs9E8GWO4WMe2+32oPJzsp6nF+iou2qAOb42uFG7B8QiXqi+2j4VQ3gfyekV8lFsiOzhb+N36I5PTHGZNW1BEQZ4Nek=,iv:HBFA8no0PB1+2Kbk2YlLYJ0HSMbzw7fkwC+eZZaFHr8=,tag:XR7/oINIak44rVOglB9BDw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
