apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:6Hg3S+7ZevqZ+WTMt+IrCPSxOtAot8OGOA48E8W4/ExmCqsiPoz81QyUQp/hXiHYS9NYCVlV2/xVgRICm1JxXhmBKFbI4EoiqpA=,iv:Xq4+HLdNcmWaa2QHd8YpsAFBIJ9/YX9Dv94AR24nsAY=,tag:XHWSR+l3wlPty+qzmm5opQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYXFMV0RHb3BNcnpWV2Yx
        cStwZjBOQzVyMHdjNWM5Z0NISGJtK1EvN1Y0CkFkcWo1czlwWFV3R1dZeEgvVHlm
        R2hhZmoxQkxaUzg4aldrYStsYUtBek0KLS0tIGdRbng4VjMzTE9hUVU4aExNb2lV
        R3ZyendpUW9jdjR3anNIc1hOOHdJYlEKstY4uB9dEJIrkuiao5aLPmYGA0WL4pjQ
        gnKZoRzK6WLsIvvoGN23gVFkZFTuJ3geAzd9iRTFqJQLf2hskI30TQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T01:56:23Z"
  mac: ENC[AES256_GCM,data:CPUsLfrYT/NwX5PY6niPHwmzDBD+ftwm8zAurHDpQ14h+yWMvWL8C/IlgjfY+g4VDjU43j8hQXBh/tN8MfFG/PwpD9U/0Cr5H3MahMxSNPhhWdog4rIg8dDJ/8/8uKrKlUrurIdtRgko2MGNkug95OqBDMLThNKlFmsfkhOqQFQ=,iv:x4VV8ROeUkGH4F9pJRWL66qMYJHIjKMS2QBwSAYyiMc=,tag:KvJX2fLnHU/fC66x1naD3w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
