---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plex
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: plex
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      plex:
        type: deployment
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.43.0.10492@sha256:8cb062f2b0660bd7811387e6c799da0ce5f18112078fe21485c11adcc83a9c1c

            env:
              TIMEZONE: '${TIMEZONE}'
              PLEX_ADVERTISE_URL: '{{ printf "https://%s:443" (first .Values.route.app.hostnames) }}'

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ 'ALL' ] }

            resources:
              claims:
                - name: gpu

              requests:
                cpu: 100m
                memory: 1000Mi

    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: plex

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [ 44 ]

    service:
      app:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: plex.svc.talos.${DOMAIN_NAME}

        ports:
          http:
            port: *port

    route:
      app:
        hostnames: [ 'plex.talos.${DOMAIN_NAME}' ]
        parentRefs:
          - name: envoy
            namespace: envoy-system

        rules:
          - backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  remove: [ 'Range' ]
            matches:
              - path:
                  type: PathPrefix
                  value: /library/streams
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: plex

      #      config-cache:
      #        existingClaim: plex-cache
      #        globalMounts:
      #          - path: /config/Library/Application Support/Plex Media Server/Cache

      media:
        type: nfs
        server: nas.hosts.alexsaphir.com
        path: /mnt/user/Media
        globalMounts:
          - path: /MediaCloud

      tmpfs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
                subPath: logs
              - path: /transcode
                subPath: transcode
              - path: /tmp
                subPath: tmp
