---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: media
spec:
  components:
    - ../../../components/volsync
    - ../../../components/nfs-scaler

  postBuild:
    substitute:
      APP: *app
      PVC_NAME: *app
      VOLSYNC_CAPACITY: &capacity 100Gi
      VOLSYNC_CACHE_CAPACITY: *capacity

  prune: true
  interval: 1h
  path: cluster/apps/media/plex
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
