---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/keda/nfs-scaler

  dependsOn: [ ]

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CACHE_CAPACITY: 25Gi
      VOLSYNC_CAPACITY: 100Gi

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true

  targetNamespace: *namespace
  path: cluster/apps/media/plex
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
