apiVersion: v1
kind: Secret
metadata:
  name: plex-secret
stringData:
  plex-token: ENC[AES256_GCM,data:LdriLAeS9avnFIG0ttilaHRvgAs=,iv:JTDqckLHf0SBczXPX79YxC3lA2np98PR5HVD60Jmg7s=,tag:SkfhV1/7rttV2R+N5r/c8w==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEJZVFZPb3g2VFJDRk9W
        RXByWDBrMFlxS2ZMYk5Lcko1d3YxcE9xV3pNCjJLbk1UbTcwdGZETlRXRDFIWFAr
        dGNmcXJCRml1UXZ0R05rRG1ZSE9MNVUKLS0tIEpoQkY4ZG9kK0NTVjl0YUM5WDh1
        MjlkUHR2N1JaaS92cVI1UVZZNmR5dHMK3C318L/lNCotWC5qP/jIa5gXdm2ea5Vf
        VyO9ZnzY7kotekDGAeP4DFjsAib08UFMXfV+JbyhB92z0gVZYlkXFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T00:27:56Z"
  mac: ENC[AES256_GCM,data:mBiiSgcT4D5McqkP79W875vumPSHMTwHPiOTBEdZGW1P3qp9//li4mcd++ynR5TMKBL4EX9GylGIBcHjbl3QdOLFEhCd1qzwBmhsL3gqKja1EeZ5lv+tZAqMmInnxlDM1XySmCmKvwXwZSNUitWKYmbJqlp/zjsKTvEHXr+NJQE=,iv:g85QUlxqX3KM3CLVQpLSYzxxnq+Nk23bKIAvChruY/Y=,tag:rP115u/2GlxPxw3lwGMdzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
