apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-restic-secret
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:WF4FogKYwHQ06ygCnB+u9+dgR5sj1KQzqB62pTPaZsaCJm2bi3Dch2lfU+5Adc0SHW0HIGCsY67hjGOgHqfKAirHRZpidu4=,iv:z0TfvFPQsaxI3iOI3qDxIGHIdlmEziCBUuyrNpVsvJs=,tag:Me30/+97iT54jhW4lR+1pw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:PZUBUy2Nja1ypmdU3LOVbEWZr96tsCA09rJE7ZTPbYeeUEL84PDk6JnFQfBPDc/322bWklBtU90/8pIf1vm3BrBbNfTEJ7qA8ZQEEYGgZQXr1x9p0ngZ0A==,iv:7hOhu53xXVqOupQTqk8GzC2TdhZMrLG6D9tEpvU6MOU=,tag:oSu2MNpeEY+O/2QgQ8cW9w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4jAIpBIasqLqlVhuHzE=,iv:/Nyp4ugfke+xvFXi9tdz+gjITqg8mbYY5JedEdIDxDY=,tag:2Gg5IqWifz+YG9f45q/s6w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KhHfwb+N+sYpVO8ueghdB9hVbxrfcWCM7I0Nqcr90+iCtNmHSxHZgCEnhkDmC4y8SAgcio6FARiDd9PjqAloAPwEoicdPAnq+pA8M2z5uFn6ehAQVVdVOg==,iv:hpgBaufowMbL/kkLMPUCc9NtHhmY5Rpklg+VejY9VWw=,tag:PAXkhbgfGBF4gfQaZJ5E0Q==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWlBFbVpkMWQvNmMwNEY0
        QTB4MWgydUpFb2h2OTUxN1FwaktCUnFqMkJzCkkvWldqQW1YMW1qSUo5eUZwZ29y
        TEdQdW5ZL2hXcndXV2JhVXBDY2Ftcm8KLS0tIHhBaGJKanhkbFRBTXpFR08vTkpw
        NUJTOENPUm13QXVIUlJuQk54NVlvWHMKAsdL/M/UKCfh4R5kSEPDUbB+dAaBvhfb
        Iz4WorwbTs3XskWRRI07OVHa4+1IejRj7kQqGJ8XPUFZNhTHTxxsrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-17T19:15:10Z"
  mac: ENC[AES256_GCM,data:VKMUhRPWN9HyjqgoLdEd6VbFormOFa9nFHz/2yTmkqHsj0t2pJSFS21FlObQSXC+ogLjS/GtfNbxe9OBrxDomBaw2jQCquur9EWrIq972bWuDnXsmbWmeE2h8XK7521gW3DtBuOqqpf7u9SqMvJ1u1bP8I9atnFWQZ7bs2B2JyY=,iv:jCxcO4yI+ZXPYYMXmWWbLpZ5PsDUJp3YZXGp6Xd/yqc=,tag:ZwAuWUdRo7GpzR4HwcGLSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
