---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: kube-system # Required for Renovate lookups
spec:
  interval: 12h
  url: https://intel.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: kube-system

  driftDetection:
    mode: warn
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
