---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: cloudflare-issuer-secret-test
    template:
      data:
        CLOUDFLARE_DNS_TOKEN: '{{ .CLOUDFLARE_DNS_TOKEN }}'

  dataFrom:
    - extract:
        key: cloudflare
