---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: &name letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: *name
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-issuer-secret
              key: api-token
