---
# base of CNPG ClusterIssuer for clients
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cluster-client-ca
spec:
  isCA: true
  commonName: postgres-cluster-client-ca
  secretName: postgres-cluster-client-ca-secret
  secretTemplate:
    labels:
      cnpg.io/reload: ''
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# used by clients for cert-based connections
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: postgres-cluster-client-ca-issuer
spec:
  ca:
    secretName: postgres-cluster-client-ca-secret
