apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-issuer-secret
stringData:
  api-token: ENC[AES256_GCM,data:qu5w5NE55D/DZpbxDhQqf0JLsqqFYB5YwHr7QpjXWjGpkcz488DsKQ==,iv:bNCQcgezwnqM/X0HuHGUfaz9APkFhTRw8yH4Ot4SjmU=,tag:EaxZKQj8AAhK/beyr4FMpg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTFpFQkRyR0EwSC9GcCtG
        QVBFQUxTZkprNjJtblVvRnFjaXl1ZnFoY1NNClVIVjNYaytzRXhMeFNoTzY3d0pn
        M1Qzcmx1cmJFL2JzMnI5Q0F6Q3FNM1UKLS0tIE1lNU9lQytySlVvNnVwWEpjUjMz
        ZytKaG1zRGE2NkNFNGMwY0d2UTN6OGcKY2Z09QAwKNS+lwgxdKHeE31at7kFzyaP
        2pXZMSG38UB70V1rV6ikG04QCIu5ieORTuJIAIAR/PIBWjm1UyzhQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:36:02Z"
  mac: ENC[AES256_GCM,data:hykktC1Da8vjjmj/jXTHwYb8jKeRquTxEV2dgsNQ04eDB70Wo32Jq/cxiYLLfdeaL/4/dPueUkeQ0eaDPgWROPYUDWVeYOK9ZQmEzBxPFqtrOMSZJqq5pp1RPcbzJuZQk79fheb1gzPfspPOoJhx1gQckBwkxh3/+EI8CMmpYfQ=,iv:Rib5EmoAMq3YQBZw7fwi8yVr0q8XLgocQPJ1IjTjIME=,tag:Xs1oHRFzArfZWhGt/doqjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
