---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2025.4.0
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: authentik

  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret

      deploymentStrategy:
        type: RollingUpdate

      env:
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: *app
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: postgres-rw.kube-auth.svc
        - name: AUTHENTIK_POSTGRESQL__USER
          value: *app
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-authentik-secret
              key: password

      envFrom:
        - secretRef:
            name: authentik-secret

    authentik:
      email:
        host: 'mailpit.kube-system.svc'
        port: '1025'
        from: 'Authentik <authentik@talos.local>'

      redis:
        host: authentik-dragonfly

    server:
      replicas: 1

      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi

      metrics:
        prometheus:
          serviceMonitor:
            enabled: true

    worker:
      replicas: 1

      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi

    geoip:
      enabled: true
      editionIds: 'GeoLite2-City GeoLite2-ASN'
      updateInterval: 8

      existingSecret:
        secretName: authentik-geoip-secret
        accountId: account_id
        licenseKey: license_key

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 128Mi

      containerSecurityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccomProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
