---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2025.2.4
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: authentik

  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret

      deploymentStrategy:
        type: RollingUpdate

      env:
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: *app
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: postgres-rw.kube-auth.svc
        - name: AUTHENTIK_POSTGRESQL__USER
          value: *app
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-authentik-secret
              key: password

      envFrom:
        - secretRef:
            name: authentik-secret

    authentik:
      redis:
        host: authentik-dragonfly

    server:
      replicas: 1

      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi

      metrics:
        prometheus:
          serviceMonitor:
            enabled: true

    worker:
      replicas: 1

      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
