---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace kube-auth
spec:
  interval: 1h
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  dependsOn:
    - name: postgres
      namespace: *namespace
    - name: mailpit
      namespace: kube-system

  prune: true

  targetNamespace: *namespace
  path: cluster/infra/kube-auth/authentik
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
