apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:8XsUVaquXvGVkWkqh6S7wfs=,iv:nnwcI9ih7HEczdhi73H4C+Q9l0AOvSwXyfZN0D70XLg=,tag:U4qpK/2NEl/M67GZ9YJfjA==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:YOoOdOIEeH5bDgBAj/B+nd8Peiven7NYufad70al+WiMW9fVOppDtYbC+e1Toa9mHLLigrqXs6Q1bwxY6wnMdjtmikJoYntTXPwBCRsSezFf4D8qrwtsPw==,iv:XlRbV/jSq89JiJeB+L1lnS3Texnwv53GJTAdxMkze+s=,tag:2sEz6EiZfDut/1ryTgB7rw==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:nfQMmqQIGty86JRgRpBX7QtdlDVvrWhVxERwEGsXwIMIScr2ka+azFYeGXl6bzKqe3VQXzuvqYh9rfOKGwZczELyIfU87QJbTe0+EdWMFbaQuEdH6nnOZA==,iv:9m0WHBGOdaUksRcBV8PwrazEgCrSETyAYzHon0uiOPA=,tag:SMZvwGi61yq9aP/m8MDg/A==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:yUExaSDUU/mYuo8QTUY8ea+rviMlcp2xoWGyt301G3it1vHo8tQCLEff7lsYE6DSt82gG9q8DpYChBQj,iv:gSyirjcKJ2d4MKSS5OMYOkJm0XP9EGutD2B9hrXBj0E=,tag:5Tf/OyfS40wDQx7BwdlQPg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMCtyTHFFNklQdEp6ZjNy
        RXFCczRVcEdCWlkxaTgvSFBkMmVXb1F5UDFBCmo1emV0bW5aRDZManhDa2hqVjhF
        WjFabjFJSm9tTStCQ0d2L3ZPM0RTT2sKLS0tIEZQK1dJMm1Qd1pQMTNsTVhxdHdx
        clcrN1lDdU5CUTViNHM4M1NVUW1ZUzQKIli88J1RWJpA1fKbDQtdsqm65CEs14YX
        Z9lncztPrW0BEKP0Uw9qMRGLXGakZWAhQYVdG5L1G4AnS6suN4jodA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:17:02Z"
  mac: ENC[AES256_GCM,data:yxGehlT7VcEr9m6CQCeVip6Kq6ySJfFPqZlR9gcGrI9RG4mgIBa197fuYJ2EFi3VzZsLTI1sHM2E627Bot++rK7Sh76zen9sOy/kV1mHVD6XobWA+XogTiMs2RUEvAWb5g9LhtlfUucll4/lmfCXYZwi1FviaLUlM74E0VGDNGw=,iv:cDSh1+KINtkZKuOSrprQuk65HjdIzbCE4T3z/+6Q04I=,tag:EzOhCQj9/NSB29h6/uDgtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-geoip-secret
stringData:
  account_id: ENC[AES256_GCM,data:8SL/X7+0,iv:kHMmhdm+rbj9Q+D96gC+PG4NG1XC9qY/1ieabqOFDz8=,tag:BukUxAWkX38EgJpvNrLm1A==,type:str]
  license_key: ENC[AES256_GCM,data:fz6NEzSaq7JK5y12EPFvIQ==,iv:97MVPC7JI0LNHTSKdK9BsCrrdPvmdVd9aVGiNdI3CkY=,tag:TLiOVJlZAIqLwh7YWuxs3A==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMCtyTHFFNklQdEp6ZjNy
        RXFCczRVcEdCWlkxaTgvSFBkMmVXb1F5UDFBCmo1emV0bW5aRDZManhDa2hqVjhF
        WjFabjFJSm9tTStCQ0d2L3ZPM0RTT2sKLS0tIEZQK1dJMm1Qd1pQMTNsTVhxdHdx
        clcrN1lDdU5CUTViNHM4M1NVUW1ZUzQKIli88J1RWJpA1fKbDQtdsqm65CEs14YX
        Z9lncztPrW0BEKP0Uw9qMRGLXGakZWAhQYVdG5L1G4AnS6suN4jodA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:17:02Z"
  mac: ENC[AES256_GCM,data:yxGehlT7VcEr9m6CQCeVip6Kq6ySJfFPqZlR9gcGrI9RG4mgIBa197fuYJ2EFi3VzZsLTI1sHM2E627Bot++rK7Sh76zen9sOy/kV1mHVD6XobWA+XogTiMs2RUEvAWb5g9LhtlfUucll4/lmfCXYZwi1FviaLUlM74E0VGDNGw=,iv:cDSh1+KINtkZKuOSrprQuk65HjdIzbCE4T3z/+6Q04I=,tag:EzOhCQj9/NSB29h6/uDgtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
