apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:W4+e3QSHry8JdIoT0oxKk1Q=,iv:w71ayqP4AWnhC/sYSSv2At/tUwmLy0H7bzmfm7XWmEk=,tag:vgyEFuO8WMvoaXGFPvYsYw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:c9sapvhuQhNzPxb9+UVYWLF0wyUz6deT08ZPv3lT0p2Dm632X+nNSgPTLWakl9ToSLkTkcMMmyVGSnjoMotQ/jIwWIk2liMtyzDgQyW0QFn+6O4vg8tnjg==,iv:DkbBSA/5h53O/q/ZgMlmsUlXD2uXQ2TRDIFnpjoMJ1s=,tag:o645nuwpYRveHIIoSNAF4Q==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:WzMIcos/7vRe9ec2RUDHrsNrnXzU9NbeM5vbQHe+gNS39MW5Yl8Cy51qdwigFPETbI6m4s/RT0HK2m/zhxFFHl+fpBf6/PjiT938Q2A3HYNXebEwu4qf3A==,iv:Q6JwVgnVmda+451sxGdf/LxeMEzaUER9TXGfI64Mfbc=,tag:nm4IASLY3N5KCrjLYng3GA==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:68aptI4ayL/jQCGJzdC0puwKRA70OShNjzyf9MmBAoAjvVyK3t1YPeWL8Gd/jPN6LRpHDk0oJbMhuEDo,iv:8FTLteB+tRdRt4ZQYjLtcLn2aR22I/8kAKjflSXKXME=,tag:IoHjZ4eCUrdoENAElOS88g==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRjBhVlpRaFloS1VSb2xx
        ell6TE1HdDc2dzFBMU4zVWh2QlhsRGtMdFUwCnBNMUFWMU5mT1orN0xJdFJXYnJt
        Nnp4NHMwV29Bc0pvMGU2a09nRGJnWDQKLS0tIEdudFRFODZEbEdqZVlFOHc3eHRp
        cmk3RkVFY1lpZzNGUVlpbElPOFpoTmcKVkzvBbM0blnGYtY3X8EHT/pq4HOqQXzb
        gsrDPEN02mlbDeLrcOvizYe47SQlmI89/O9xO4/e1kjgdT/oMShI7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T01:08:02Z"
  mac: ENC[AES256_GCM,data:8qvmqzbrY7P/iw84wThpJlTeMHOGLNtQ+l8OnuvGTmlbD50mO8pRh9BE5a2KUIKnneG2GMGD/tzSly3H9MfMRG9Iu23iQY82n/GGzaqvCHrH4vbzgIDdi3roluw8XOyAR8ytSjOkZ4dbuRH8Ys1A7DF41Pw2kb7UdmyXkntA0lw=,iv:tdM2uFLVdulCyfuWib8r3r4PJMDOWTWm05WZ94qtFoQ=,tag:0i5uvj3XA/+LihyEWjjlOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
