---
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: nas-disk-high-utilization-disk
spec:
  matchers:
    - name: alertname
      value: NodeFilesystemAlmostOutOfSpace

    - name: instance
      value: nas.hosts.alexsaphir.com:9100

    - name: mountpoint
      value: '^/mnt/disk[0-9]+'
      matchType: =~

---
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: nas-disk-high-utilization-shfs
spec:
  matchers:
    - name: alertname
      value: NodeFilesystemAlmostOutOfSpace

    - name: instance
      value: nas.hosts.alexsaphir.com:9100

    - name: device
      value: shfs
