---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name timescaledb
  annotations:
    kyverno.io/ignore: 'true'
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'

spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 17

  postgresUID: 1000
  postgresGID: 1000

  instances: 3
  enablePDB: true

  superuserSecret:
    name: timescaledb-superuser
  enableSuperuserAccess: true

#  bootstrap:
#    recovery:
#      source: source

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: *name

  postgresql:
    shared_preload_libraries:
      - timescaledb

    parameters:
      max_connections: '200'
      max_slot_wal_keep_size: 5GB
      shared_buffers: '128MB'

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  resources:
    requests:
      memory: '512Mi'

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true


  managed:
    services:
      disabledDefaultServices: [ 'ro', 'r' ]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: timescaledb-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: timescaledb.svc.talos.${DOMAIN_NAME}

            spec:
              type: LoadBalancer
              ipFamilyPolicy: PreferDualStack
              externalTrafficPolicy: Local
