---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 17
      image: timescale/timescaledb-ha:pg17-ts2.24@sha256:5256b6c66d20eba710281fc7b828f3c70913103291381cc6d78b84fef1759fe8
