---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 17
      image: timescale/timescaledb-ha:pg17-ts2.24@sha256:c8ae2f0fb18a8f715d307082dd0d92d5a58cefdfa744de31a367c947fc190b73
