---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: timescaledb
  namespace: &namespace database
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: cloudnative-pg

  healthChecks:
    - apiVersion: v1
      kind: Pod
      name: timescaledb-1
      namespace: *namespace

  prune: true
  interval: 1h
  path: cluster/infra/database/timescaledb
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
