apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-superuser
stringData:
  username: ENC[AES256_GCM,data:OZAu1ry1/p4=,iv:7LMPOSLnoAyEUqjvFOzzAGcrICAhzDHjzHwjExGl9gw=,tag:gR/3lrQwRvmTJObOXD9rzg==,type:str]
  password: ENC[AES256_GCM,data:PKwe/66+o7FCScwccBObicvbxWEHRLnGXK6S/iYDwKwi3kCqXhutv1MeIlFSRZ6mS4PxNgXqsetGjqkBO7feCKhqh/4C1pozHLBeadPVFBtgdC887ebVkw==,iv:UHYVpJtFL1VZJLkDgSuX8emGHxvt6OSrv0Qr48PQe8I=,tag:YH922rMnZx3jW2dWK76kpg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbEc4elZOWk1VeVErY25p
        cExSbEEwVnpRelJxOGxaRU1xYVZwb1pCaVhBCmVzaWRRWXVzVzNpV1U4MTNWdWxY
        dlJ2MjBUblEyMnNhR0svVllFa0tXdUEKLS0tIERVVUMyTWRxUjQvdlFoT3hZeXkw
        T0p5Y3BMNGJPcitSbXRiakVOejRFbDQK8iQrDzZhgTj9t07BnFutwK6PKZoyke1v
        bzif1lrYlg9NDlwhqUHnpxYHeXW91Ros/JzjsDhAMx60Jk+IwGu3bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T19:12:48Z"
  mac: ENC[AES256_GCM,data:/h90hnwfATjriyi37bHR1FcoTX7L9LegiKr5BL6w9KSlPuow/3nkzWzqx5uDynab48Q1QMGHHHyo2xWLLHPeBmnLVB/cE8FvkXmsN77LY04WW/9IlsNg8EwPV6mhwRvTzYaDaPnvdEVS0Oee/kgGOyhXbD/GRZcX+sLzY6rWpMA=,iv:RVAkmIqanes25a7JlupxAkOfRaU+AZDxUmiVEwkIXoc=,tag:OhysXMD4u2edkdfJzk0iPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
