log syslog
!
hostname UCG-Fiber
frr defaults traditional
!
router bgp 64600
  bgp router-id 192.168.0.1
  bgp log-neighbor-changes
  no bgp default ipv4-unicast

  ! Uncomment the next 2 lines to disable ECMP
  ! maximum-paths 1
  ! maximum-paths ibgp 1

  no bgp ebgp-requires-policy

  ! Peer group for Cilium nodes
  neighbor cilium-v4 peer-group
  neighbor cilium-v4 remote-as 65100
  neighbor cilium-v4 timers 3 9
  neighbor cilium-v4 timers connect 5

  neighbor cilium-v6 peer-group
  neighbor cilium-v6 remote-as 65100
  neighbor cilium-v6 timers 3 9
  neighbor cilium-v6 timers connect 5

  ! Enable dynamic neighbor discovery
  bgp listen range 192.168.42.0/24 peer-group cilium-v4
  bgp listen range 2a01:e0a:2a:5552::/64 peer-group cilium-v6
  bgp listen limit 16


  address-family ipv4 unicast
    neighbor cilium-v4 activate
    neighbor cilium-v4 soft-reconfiguration inbound
    network 192.168.43.0/24
  exit-address-family

  address-family ipv6 unicast
    neighbor cilium-v6 activate
    neighbor cilium-v6 soft-reconfiguration inbound
    network 2a01:e0a:2a:5557::/64
  exit-address-family
exit
