---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: 'No'

  blocks:
    - start: 192.168.43.2
      stop: 192.168.43.254

    - cidr: 2a01:e0a:2a:5557::/64
