---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: planka-prod
components:
  - ../../../components/namespace
replacements:
  - path: ../../../components/replacements/ks.yaml
resources: [ ]
