---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: seer-secret
    template:
      data:
        API_KEY: '{{ .SEER_API_KEY }}'

  dataFrom:
    - extract:
        key: seer
