---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: seer
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seer
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: seer

  values:
    controllers:
      seer:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: develop@sha256:e369f96c735efb3f558f3143c56b1727d54702f45e2faa2820020935abc761d6

            env:
              TZ: '${TIMEZONE}'
              LOG_LEVEL: 'info'
              PORT: &port 80

              DB_TYPE: postgres
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: &db-secret 'database-{{ .Release.Name }}'
                    key: HOST
              DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: *db-secret
                    key: DATABASE_NAME
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: *db-secret
                    key: LOGIN
              DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *db-secret
                    key: PASSWORD

            envFrom:
              - secretRef:
                  name: '{{ .Release.Name }}-secret'

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ 'ALL' ] }

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ['[STATUS] == 200']
            group: media
        hostnames:
          - '{{ .Release.Name }}.talos.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system

    persistence:
      config:
        existingClaim: '{{ .Release.Name }}'
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
