apiVersion: v1
kind: Secret
metadata:
  name: seer-api-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:L++AoRmNZYTvlNNhr6UCsFWxGK8I1I3d/8AyfWar2gnv9/Irk47E+vrIv0BAeEWyiSVx8QPjBykj2/Amt4QVc3105HU23kekAPpVrMdiMpc1OYjuFZHKWQ==,iv:LjVl1DKofjsN3M9HyJiYrTGI9kNuFptDD5L7jSSAOUw=,tag:Q586lKn/qjvm5qaHWOZmRA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYllkVHRJbVNQbjAvNnV1
        MEhLMmg4OUJKRW10d0MwL3o1cllPL2krNWpNCnFrSUJkUTN4V2dVZDFUUHpKNHc1
        NGxXNDZzanVxbUJIVE9kb3h0NysrbUkKLS0tIHhhOHNKTmo4VytGeU15M0tJdDl4
        MWNBTzVlRDFLaUZjVDVWOVZaNGZEYmcKYhLAIcBuY8W6ODhemD1WybX10xMgfUfM
        XCHeFXcee8oj/lWfqMJSfZbIXSwhYSrwBe5Cgbv41LwS0br4pM27xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T22:57:31Z"
  mac: ENC[AES256_GCM,data:D8E6F9M4a91SptmXC3weRgdNPUlcpQ8PaGatg1dPvgQCDDRKUuwlGpjz6lFUYZuWO3HqOt+Fji0mDEzQL//Q5ypE+Ijmj0ygKYLP1HWzLk+0z2cEdp6Q1NWG7CGLYWhKuvsm4eOvKeLGZxe4e6XxvLb9q7iqR4lf+HfJxht9rGg=,iv:GJ159z33p8mOTtfDxWFbQchppmol2xpHNU7Q2MamANs=,tag:7F0jyzlbIML6KHeVt/7ddQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
