apiVersion: v1
kind: Secret
metadata:
  name: seer-secret
stringData:
  api_key: ENC[AES256_GCM,data:h6xfvmzmUWzRWwbz3cX43Xcn5O2oB+HzcXA04QkeFEp81Cu4b6ALa7ia3Bas3AFV9cJEFUXI+/r2bXf6ZP+SJAbR2F8EoG76bMKaCdr1P1Oujr0ilaSC1g==,iv:r7jdfBzRQdKuCJpez3AK/0pUsiVRdcYuEwR4GY5RoL8=,tag:pALtguLRkpTRhUKI+mCeRQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc0ozNzFwOWlnYVRzcy9J
        ZUMydmxvdXpKeHJtSStnV3lYd0ZFaExGMHpJCitxMkJUVldCNDJHeU9jNWkyYVhz
        VE1acU13S2VWVDBFUnJtbmV6ckZJcnMKLS0tIGJxd1VkeEp3bTZOWUVHTWpCaDlT
        eHZvS3pFR2FXZU5zNHNzSHEvcWoxQWMK8h5EWBujE1m2ipnCFvZsHcv2OWkt334j
        CzZh9CFKiaCSk4QFDSYSylyH/75jLAHC0c0Pqmxphsad4oKrgaUOrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T00:46:24Z"
  mac: ENC[AES256_GCM,data:x19WjHBO3FORBt1mNDEn3XFSAfUtGa0VPe7GmfYhZ9/A6+9572xCfk+yYihHPYhR0mpysUvrKSEGhtljGC7t0UO3DT9z8nzmpd8/sU/V6ukOAoPYuFpFoYJ5p0/lfTS7TNx/mgbXiclImN5eFrDdDRtZustXxZdcn8k8tDlPVCs=,iv:IwJGYGJh1Rzi39n0lwEx5h0IiTThV1cuYcf5A7BuEZs=,tag:ZzZ4lP+O6jFEABc2hnj5hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
