---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gitlab-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 5m
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: gitlab-config-tpl
            items:
              - key: config.rb
                templateAs: Values

  dataFrom:
    - extract:
        key: gitlab-minerva
    - extract:
        key: minio
