---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gitlab-minerva
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name gitlab-minerva
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *name

  values:
    controllers:
      gitlab:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: gitlab/gitlab-ee
              tag: 18.9.2-ee.0

            env:
              TZ: ${TIMEZONE}

              GITLAB_LOG_LEVEL: 2
              GITLAB_RAILS_RACK_TIMEOUT: 6000
              GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false


    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: false
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 80
          registry:
            port: 5050
          pages:
            port: 8091

    route:
      app:
        hostnames:
          - 'gitlab.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system
        rules:
          - backendRefs:
              - identifier: app
                port: 80
      registry:
        hostnames:
          - 'registry.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system
        rules:
          - backendRefs:
              - identifier: app
                port: 5050
      pages:
        annotations:
          external-dns.alpha.kubernetes.io/controller: none
        hostnames:
          - '*.gitlab-pages.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system
        rules:
          - backendRefs:
              - identifier: app
                port: 8091

    persistence:
      patch:
        enabled: true
        type: secret
        name: '{{ .Release.Name }}-config-secret'
        globalMounts:
          - path: /opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub
            subPath: license_key.pub
            readOnly: true

      config:
        enabled: true
        type: secret
        name: gitlab-config
        globalMounts:
          - path: /omnibus_config.rb
            subPath: config.rb
            readOnly: true

      data:
        existingClaim: '{{ .Release.Name }}'
        advancedMounts:
          gitlab:
            app:
              - path: /etc/gitlab
                subPath: config
              - path: /var/log/gitlab
                subPath: logs
              - path: /var/opt/gitlab
                subPath: data
              - path: /opt/gitlab/etc/gitlab-kas/env
                subPath: kas-env

      tmpfs:
        type: emptyDir
        advancedMounts:
          gitlab:
            app:
              - path: /gitlab-tmp
                subPath: gitlab-tmp
