apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minerva-config-secret
stringData:
  license_key.pub: ENC[AES256_GCM,data:ZXO+X6rcHr0LdZ6d3M7KTAGYI/pRC7M0DRCg06HdOZN3Jxnjbc3Tg6kOgXPiarnfKWATQjQa7wgUl27Q28u/8krLkB6kbxgOkQx/wpeypyzItJAAXmcgnNvaeewXgu4mX0r+MGUZ+cB+iDnFXK9WLpQPmZsNaFT98vp7NOpzwl+QZXSbyZ59mjgagBL2y72YuTerQEKaLrYoi46PI/Poc0un5mEn8E6ByiM4eR+uOH2lMmPlx746unk+khPPcDzR3v7rmwp4sNiy3zv19mrAI9i69Zlf5N/d8wz7fds7lQykOYg9THTyj41nA0CIw1bIIqQBCM3vpfELm6I1Bb0K+IMzEyiCCyuBHzCoEvSMiSnWo9EpzpU+D5YxBfhBu4z4NyuBsv0rb3iqKxd66uay43M1NcHxWyc4Gtumm+ezxYR0KdFPSmZblaJBMYADwY9w75cCIbk3z4/HiLbvKpqP0lDBRy4Kheuss+NAx1lPJYPX9/Mdz4nsRLznyHrHOi7Cp4i87RyRCkeOl3G0fhS9gabwZiPa/3blCjYUnKmtWjjRALqf5Y+tQCjf6WlrIyJk9XCkJUxsFdF+zDvCQs+WP6LYqg==,iv:qGb4wh8+Nmy0BNg6EfxpVz82bNt6jgt1PKEoQZT+cyo=,tag:JyyGep8u0IxzXRSHQ8TrOg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZURUQTBjV29LOHczSDc5
        ZGY1M1owMWU0MVRpNnBGOC9LSVI1aGpsd2hJCmxkMEJaVzFmM2p4TnhkTklaWGlp
        TXBVVlZlZjBaSklkYWJ5a09ET3FOejAKLS0tIHhOL1J6WnZWLzFaWG1YeXkwck8y
        bk1ITWFacXU3RWZNSXlzdzREK3huSHMKQdXRwz51hu2OfAB7zNFlAHVc/1olQd0w
        0bTVQnBiXDhy749FydKCX1w+NqZD1ElU8IekA0gJ3mSqj2pxj2A9zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T20:11:56Z"
  mac: ENC[AES256_GCM,data:P/tkNeYdNscgQredmm9SVjnURzJotA/9dkNEiSenBprqs0mTCJhHh5CILjqlkAkWgBZmPijWDiIu7DPy37UjycNWsgUSaiSwihkl8Hpnuf9k9/2ZqH+7iirjKfsSq8gtz4bxgHjgLYHOL0w+LiSu/4rE1m3HuWdo+qmFzAt+DPQ=,iv:88Eca6KdDN1cn98VMBUnWbHYQpidPQ0n/2XBNmHGXhw=,tag:sm0rK6DmZRBROXHlkSgypQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
