apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minerva-config-secret
stringData:
  license_key.pub: ENC[AES256_GCM,data:+YRytD4/Z1yPczEp4qrcS1QsTDHMeuT2pU/+FT5BmLeYjtkwruO3IDQI2xlzbgEteKQ5clLdmvCS4rlxF0SlyPwL671VnFx8EiIK4ig7E3W7oyHXpWC/69nvKjETB6WA+s1pXnj//m2YCzRnEJqby+Gt1jU6LfvJ99u2XJquTu1R/utE8V1guDQ45ndYopuA+stdl1vwZRmFMXEBfvCrEjc7ZbObNlmLH3eN/DL8/p+/nZpxOvE9aFlOlkUfGeGaCYH118xun+hKObhwX2OThEokHlQ98ui5JBwWWESyJt7wVsqb0bDBstAPe8qqRs/DiobD2e17PtYGQ3a6aNSO4XNyEwiDDfna5C1IVc8XZPD7yJErJawh41Fvr7glX3vEV0c0SLHtQoDZOvQsYZECcZKNUJGsuxvE4xfF+YSz+KFVx8Wyc9cBwUte1x1d6F1LsJBYajazvpfL1e21Ko2j4Mr2V6nBwvad/60qExuACdqdZFL1ufDHtvn1b2ksE2/FJ0ak0m9ZIY8fQQk32FPBjqQsI3BUIdOxPL8i6b7hRGNQBGK4agXylf3c6+7A576dWAwziwBPV8FUelKPT1C6P1PDFQ==,iv:ure2mXNF2gviV0UlJJWaAdtL4SMD/jnmzCbnP4Tb8I4=,tag:00J8B0SAy7aM61d/G8rkUw==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcG55NXBWb1R2c2I1MnhZ
        Yk5SRVZodThlUGVYVlZEdG9rYUVwN0N0RW5FClhjYXZyTzJRRTlJWm8rb2ptYW9H
        eVlRVHFjczhDTktMdms0eFpqdUVIaUkKLS0tIGJVWVkzMDVaM3Z1ckxaRnhud3cy
        SFNPZ3ExeFV3VEZPM28xS2tCV3RlM28KWPvbBrMMjm4tJ+W6oo6AcR/f/c7yaXpC
        YAR1LvCY9wT4wPqq/iLjRZtniMuG/iOhfwR9fquXeTsm2JfzCCasMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T23:38:40Z"
  mac: ENC[AES256_GCM,data:JE8Sg2E0LjxT5L/YyV8Ax9IOyMVlr1kwb6dTFFrZ/9pzIvp1Fh4atHBYwIdCFuVsuJks+40Ur7rQLfZifJf7qJZPj2nRXzX7jG6dDaqYtGqga1/yGFCnZmzUw9HdWzmFH8zivoy0V8sChLu6z6uq7cG117mWH/QXD8tUjhuSGfw=,iv:mb7+RdSEFBiaZ7pI5tEFJzjOdzqIrNBGzYOGZWcESIs=,tag:Ax9IxaN+Md6Molp7PMUpIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
