---
version: "3"

tasks:
  get-disks:
    desc: Get disks of a node. [IP=required]
    cmd: talosctl get disks -n {{.IP}} --insecure -o yaml | yq eval '. | select(.spec.transport == "nvme") | .spec'
    requires:
      vars: [ IP ]
    preconditions:
      - talosctl config info
      - which talosctl

  get-links:
    desc: Get network interfaces of a node. [IP=required]
    cmd: talosctl get linkstatus -n {{.IP}} --insecure -o yaml | yq eval '. | select(.spec.type == "ether")'
    requires:
      vars: [ IP ]
    preconditions:
      - talosctl config info
      - which talosctl

  get-links-up:
    desc: Get network interfaces of a node that are active. [IP=required]
    cmd: talosctl get linkstatus -n {{.IP}} --insecure -o yaml | yq eval '. | select(.spec.type == "ether") | select(.spec.linkState == "true")'
    requires:
      vars: [ IP ]
    preconditions:
      - talosctl config info
      - which talosctl
