---
version: "3"

tasks:
  talhelper:generate-config:
    desc: Generate the clusterconfig from `talhelper.yaml` for Talos.
    dir: '{{.TALOS_DIR}}'
    run: once
    preconditions:
      - test -f {{.TALOS_DIR}}/talconfig.yaml
      - test -f {{.TALOS_DIR}}/talsecret.sops.yaml
      - which talhelper sops
    cmd: talhelper genconfig

  talhelper:kubeconfig:
    desc: Regenerate the kubeconfig.
    dir: '{{.TALOS_DIR}}'
    cmds:
      - until talhelper gencommand kubeconfig --extra-flags="{{.ROOT_DIR}} --force" | bash; do sleep 5; done
    preconditions:
      - test -f {{.TALOS_DIR}}/talconfig.yaml
      - which talhelper

  apply-clusterconfig:
    desc: Apply clusterconfig for a Talos cluster
    dir: '{{.TALOS_DIR}}'
    vars:
      CLUSTERCONFIG_FILES:
        sh: ls {{.TALHELPER_CLUSTER_DIR}}/{{.TALOS_CLUSTER_NAME}}-*.yaml
    preconditions:
      - which ls talhelper talosctl yq
      - test -f "${TALOSCONFIG}"
    cmds:
      - for:
          var: CLUSTERCONFIG_FILES
        task: _apply-machineconfig
        vars:
          asd:
          FILENAME: "{{.ITEM}}"
          HOSTNAME:
            sh: yq '.machine.network.hostname' < '{{.ITEM}}'
          DRY_RUN: "{{ .DRY_RUN }}"
          INSECURE: "{{ .INSECURE }}"

  apply-node:
    desc: Apply Talos config to a node [NODE=required]
    dir: '{{.TALOS_DIR}}'
    deps:
      - task:talhelper:generate-config
    preconditions:
      - which talhelper talosctl yq
      - test -f "${TALOSCONFIG}"
      - talosctl --nodes {{.NODE}} get machineconfig
    requires:
      vars: [ NODE ]
    vars:
      FILE:
        sh: ls {{.TALHELPER_CLUSTER_DIR}}/{{.TALOS_CLUSTER_NAME}}-{{.NODE}}.yaml
    cmds:
      - task: _apply-machineconfig
        vars:
          FILENAME: "{{.FILE}}"
          HOSTNAME: "{{.NODE}}"
      - talosctl --nodes {{.NODE}} health

  upgrade-node:
    desc: Upgrade Talos on a single node [NODE=required]
    dir: '{{.TALOS_DIR}}'
    preconditions:
      - which talhelper talosctl yq
      - test -f "${TALOSCONFIG}"
      - talosctl --nodes {{.NODE}} get machineconfig
    deps:
      - task: talhelper:genconfig
    requires:
      vars: [ NODE ]
    vars:
      FILE:
        sh: ls clusterconfig/{{.TALOS_CLUSTER_NAME}}-{{.NODE}}.yaml
      TALOS_IMAGE:
        sh: yq '.machine.install.image' < "{{.FILE}}"
    cmds:
      - talhelper gencommand upgrade --node {{.NODE}} --extra-flags "--image='{{.TALOS_IMAGE}}' --timeout=10m" | bash
      - talosctl --nodes {{.NODE}} health

  upgrade-k8s:
    desc: Upgrade Kubernetes
    dir: '{{.TALOS_DIR}}'
    cmd: talhelper gencommand upgrade-k8s --extra-flags "--to '{{.KUBERNETES_VERSION}}'" | bash
    vars:
      KUBERNETES_VERSION:
        sh: yq '.kubernetesVersion' {{.TALOS_DIR}}/talenv.yaml
    preconditions:
      - talosctl config info
      - test -f {{.TALOSCONFIG}}
      - which talhelper talosctl yq

  reset:
    desc: Resets nodes back to maintenance mode
    dir: '{{.TALOS_DIR}}'
    prompt: This will destroy your cluster and reset the nodes back to maintenance mode... continue?
    preconditions:
      - which talhelper
    cmd: talhelper gencommand reset --extra-flags="--reboot {{- if eq .CLI_FORCE false }} --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL{{ end }} --graceful=false --wait=false" | bash


  _apply-machineconfig:
    internal: true
    desc: Apply a single Talos machineConfig to a Talos node
    preconditions:
      - which talosctl
      - test -f "{{.FILENAME}}"
    requires:
      vars:
        - HOSTNAME
        - FILENAME
    vars:
      MODE: '{{.MODE | default "auto"}}'
    cmds:
      - talosctl apply-config
        --nodes "{{.HOSTNAME}}"
        --file "{{.FILENAME}}"
        --mode="{{.MODE}}"
        {{ if eq "true" .INSECURE }}--insecure{{ end }}
        {{ if eq "true" .DRY_RUN }}--dry-run{{ end }}
