apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:Z+QoBthXveHzCxGjOJpi5R94eLpDEREe5VuqdKhI5thKiNkNjnQJXscFY46B7qgB/AUSgSKgIHHFx/qNn7kwaVX9MsUwMWAJwgrU2Yw+3Du78UBc2JBS8g==,iv:FdPHn0wKv2tVa62uKb9YI0yL5hdmtz6eAEO3iAvzTVs=,tag:FSMESCVrpwIKa2mKPYbFRA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RkJLbGFtNEo0NGxiaVBS
        b1VRQjByN0JHWEVZRE10NmlJLzVNZkhRYzFvCi82ZE5KTXBoRzBocmtSTVJheWNS
        bUlaODlEcWFqWGEwT1h4cExqcElSZ3cKLS0tIFFIcUVaNVExK2JIcTNGSWY3Ritv
        emZhUkVaV2JITDhnUmREc3F5bnY4Y3cK8MIvxn5LXQdszhZS1AxZHS2kQGMsrJHr
        wC/blI2g45tP3xePmOmzZAgafPPO8cFPC1+PjZUaIC5gJolAlxVV6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-27T23:51:32Z"
  mac: ENC[AES256_GCM,data:NKC2896vgKl0xf8lsAw/aKJwJAM+ReGMgLguIu6cTfXmC2WW6LB/G+zXOYMCSjcA7hPhOPxfAFPpktgQbDgzwmTleJYbOhxo/ZLqwg3iMFlj+FQ5Mm1DPQsKuG69b8Q33uOxOZLAHn11SrTL1BVKrAFkf/4kS9zEBqD8v+G0fMs=,iv:PYXE683QxjuvaRMQP5kJYI1Lofwl3jDEOOdM7vEHQIQ=,tag:zBxCDuIfAYtMU2ngz0bKfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
