---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_LATITUDE: '{{ .HOMEPAGE_VAR_LATITUDE }}'
        HOMEPAGE_VAR_LONGITUDE: '{{ .HOMEPAGE_VAR_LONGITUDE }}'

  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: unifi
