---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_LATITUDE: '{{ .HOMEPAGE_VAR_LATITUDE }}'
        HOMEPAGE_VAR_LONGITUDE: '{{ .HOMEPAGE_VAR_LONGITUDE }}'

        HOMEPAGE_VAR_PLEX_API_KEY: '{{ .PLEX_TOKEN }}'
        HOMEPAGE_VAR_TAUTULLI_API_KEY: '{{ .TAUTULLI_API_KEY }}'

        HOMEPAGE_VAR_IMMICH_API_KEY: '{{ .IMMICH_API_KEY }}'

  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: homepage-token
    - extract:
        key: plex
    - extract:
        key: tautulli
