---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: error-pages
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: error-pages
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: error-pages

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }

    controllers:
      error-pages:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/tarampampam/error-pages
              tag: 3.8.0@sha256:6fda7ff61de68b3b188538221f718d834fd9aa6ddaf0c13044febc6100515fd1

            env:
              TEMPLATE_NAME: connection
              SHOW_DETAILS: true

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                cpu: 5m
                memory: 16M
              limits:
                memory: 32M

            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: { drop: [ 'ALL' ] }

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - error-pages.talos.${DOMAIN_NAME}
        parentRefs:
          - name: envoy
            namespace: envoy-system
