---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter/ks.yaml
  - smartctl-exporter/ks.yaml

  # GPUs
  - dcgm-exporter/ks.yaml
  - intel-gpu-exporter/ks.yaml
