---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-codecov
  annotations:
    kyverno.io/ignore: 'true'
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'

spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 17

  postgresUID: 1000
  postgresGID: 1000

  instances: 1
  enablePDB: false # TODO: Remove when more than 1 node.

  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: codecov
      owner: codecov

      dataChecksums: true

      secret:
        name: postgres-codecov-secret

      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;

  postgresql:
    shared_preload_libraries:
      - timescaledb

    parameters:
      max_connections: '200'
      max_slot_wal_keep_size: 5GB
      shared_buffers: '128MB'

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  resources:
    requests:
      memory: '512Mi'

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true
