apiVersion: v1
kind: Secret
metadata:
  name: postgres-codecov-secret
stringData:
  username: ENC[AES256_GCM,data:VAILHewfWw==,iv:+YXlIRUFAIcY9yBUAGsbCyi6ztuh79Whi9ws2RLrpXY=,tag:9b9gKz+Nm5Rd1t4NrSNE0Q==,type:str]
  password: ENC[AES256_GCM,data:crlvNPBEsGogGtTxlpF7QEVj3A+FQQuNpsIuxhdYygGm9Fy27zSYoT8sNaYCTAPeUDhGB4/YURNpqlYa4XsuhsOxT3FR631UKeKvYVgoVcO8ehhjkjmhXQ==,iv:owM5sAxyRX9B8kWE8SfGBU2f6JwrLANnc4TFXlyiaWU=,tag:2FvaVSOLSNyc/WNlGTGSwg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod2hPam5XMWFZNTF2MURT
        ZDdYMzM0eGNCc09yQS9oZSs1emEyN3IrZ0E0CjE4WTdKNVNWZEU5R3ZtaTE0VFor
        SE5rMGVPQVoxRlpjZGhKN1hjR1IrSTgKLS0tIENyc2FvQ0ZyQXVPNU1ZbkV1NVBG
        N3Z1aU1DalJxZWROakc5eFVLelBxVEEKbG5DlSbbAJ3JRPk3QG46jbQEH6ufsZkI
        3a7kp73zzGa8TKHPlZhWqb83IzJFMHXkPuYH6eznQY/mqpK4GhQfRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T13:48:19Z"
  mac: ENC[AES256_GCM,data:g3o+dfMxqTEI3QwLBUdQX/WFE5RXk53G13En1hMHPJelOXkD32jzLStv9PGJmn2MpXu+1rjkIZA8GI+OOLIUZS++mkc6WOO+4bl2RGsbaKzdEt3er8Kz507hADY1LbkYOSzUSqN5lfEopN23283GIi1CVWEXsCmYaOGgQBqdi+Q=,iv:nUtXoZxNGFfIMqCQAmUZMMGc5oCPyIWkoZmvdu8OTws=,tag:osI2JYGNb3WNHQKcORwryQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
