---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foundryvtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: foundryvtt-secret
    template:
      data:
        FOUNDRY_USERNAME: '{{ .FOUNDRY_USERNAME }}'
        FOUNDRY_PASSWORD: '{{ .FOUNDRY_PASSWORD }}'
        FOUNDRY_ADMIN_KEY: '{{ .FOUNDRY_ADMIN_KEY }}'
        FOUNDRY_PASSWORD_SALT: '{{ .FOUNDRY_PASSWORD_SALT }}'

  dataFrom:
    - extract:
        key: foundryvtt
