# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: &clusterName talos-cluster

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.100:6443


additionalApiServerCertSans: &sans
  - 127.0.0.1
  - &talosControlplaneVip 192.168.0.100
  - talos.cluster.alexsaphir.com
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ms-01"
    ipAddress: "192.168.0.113"
    controlPlane: true
    installDiskSelector:
      serial: S7GCNL0XA11778T
    machineDisks:
      - device: /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_1TB_S7GCNL0XA16195E
        partitions:
          - mountpoint: /var/mnt/extra
    machineSpec:
      secureboot: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:7a:c6:c8"
        dhcp: false
        addresses:
          - "192.168.0.113/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.254"
        mtu: 1500
        vip:
          ip: *talosControlplaneVip

    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'

    nodeLabels:
      'node.longhorn.io/create-default-disk': 'true'

    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=1
          - apparmor=0              # Less security, faster puter
          - init_on_alloc=0         # Less security, faster puter
          - init_on_free=0          # Less security, faster puter
          - mitigations=off         # Less security, faster puter
          - security=none           # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter

        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/mei
            - siderolabs/thunderbolt
            # Coral
            - siderolabs/gasket-driver
            # Gpu
            - siderolabs/nvidia-container-toolkit-production
            - siderolabs/nvidia-open-gpu-kernel-modules-production
            # Longhorn
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

    patches:
      - "@./patches/nodes/ms-01/sysfs.yaml"
      - "@./patches/nodes/ms-01/nvidia.yaml"
      - "@./patches/nodes/ms-01/thunderbolt.yaml"
      - "@./patches/udev/intel-gpu.yaml"
      - "@./patches/udev/thunderbolt.yaml"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-local-storage.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: controlPlane

  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"
