---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-main
spec:
  secretName: wildcard-main-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: ${DOMAIN_NAME}
  dnsNames:
    - '${DOMAIN_NAME}'
    - '*.${DOMAIN_NAME}'
