---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare
spec:
  endpoints:
    - dnsName: envoy.talos.${DOMAIN_NAME}
      recordType: AAAA
      targets:
        - 2a01:e0a:2a:5557::43:100
    - dnsName: envoy.talos.${DOMAIN_NAME}
      recordType: A
      targets:
        - 192.168.43.100
