---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-monitor.yaml
  - gateway-class.yaml
  # certificate:
  - certificates.yaml
  # gateways:
  - main
  # HTTPRoute:
  - redirect-to-https.yaml
