---
version: "3"

vars:
  FLUX_CLUSTER: 'cluster/flux/cluster'

tasks:
  get-images:
    desc: Get images.
    cmd: |
      uvx flux-local@latest get cluster \
            --path {{ .FLUX_CLUSTER }} \
            --all-namespaces \
            --enable-images --only-images \
            --output yaml

  diff:
    desc: Generate diff
    preconditions:
      - dyff version
    requires:
      vars:
        - name: FLUX_RESOURCE
          enum: [ 'ks', 'hr' ]
    vars:
      BRANCH_ORIGIN: main
    env:
      DIFF: 'dyff between --ignore-order-changes -l -g -o gitlab'
    cmd: |
      uvx flux-local@latest diff {{ .FLUX_RESOURCE }} \
            --path {{ .FLUX_CLUSTER }} \
            --branch-orig {{ .BRANCH_ORIGIN }} \
            --all-namespaces

  test:
    desc: 'Test'
    cmd: |
      uvx flux-local@latest test \
            --path {{ .FLUX_CLUSTER }} \
            --enable-helm \
            --verbose \
            --all-namespaces

  build:
    desc: build
    requires:
      vars:
        - name: FLUX_RESOURCE
          enum: [ 'ks', 'hr' ]
    cmd: |
      uvx flux-local@latest build {{ .FLUX_RESOURCE }} \
            --path {{ .FLUX_CLUSTER }} \
            --all-namespaces
