---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-maintenance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: volsync-maintenance-secret
    template:
      data:
        KOPIA_FS_PATH: /repository
        KOPIA_PASSWORD: '{{ .KOPIA_PASSWORD }}'
        KOPIA_REPOSITORY: filesystem:///repository

  dataFrom:
    - extract:
        key: volsync-kopia
