---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - service-monitor.yaml
configMapGenerator:
  - name: envoy-gateway-values
    files:
      - values.yaml=helm/values.yaml
configurations:
  - helm/kustomizeconfig.yaml
