---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: authelia-secret
    template:
      data: { }

  dataFrom:
    - extract:
        key: authelia
