---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authelia-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 5m
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: authelia-config-tpl
            items:
              - key: configuration.yaml
                templateAs: Values

  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: authelia-oauth
