---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authelia
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app

  values:
    controllers:
      authelia:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.39.16@sha256:edbce01c5125249e4f4faea01e0f76f0031d64b4a1d0c2514a0ca69cb126d05f

            env:
              TZ: '${TIMEZONE}'

              AUTHELIA_SERVER_DISABLE_HEALTHCHECK: 'true'

              AUTHELIA_SERVER_ADDRESS: tcp://0.0.0.0:80
              AUTHELIA_TELEMETRY_METRICS_ADDRESS: tcp://0.0.0.0:8080
              AUTHELIA_TELEMETRY_METRICS_ENABLED: 'true'
              AUTHELIA_THEME: grey

              X_AUTHELIA_CONFIG: /config/configuration.yaml,/config/configuration-rules.yaml
              X_AUTHELIA_CONFIG_FILTERS: template

              AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: 'ldap://lldap.kube-auth.svc.cluster.local:389'


              AUTHELIA_STORAGE_POSTGRES_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: database-authelia
                    key: DATABASE_NAME
              AUTHELIA_STORAGE_POSTGRES_ADDRESS:
                valueFrom:
                  secretKeyRef:
                    name: database-authelia
                    key: HOST
              AUTHELIA_STORAGE_POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: database-authelia
                    key: LOGIN
              AUTHELIA_STORAGE_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: database-authelia
                    key: PASSWORD

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ 'ALL' ] }

            resources:
              requests:
                cpu: 5m
                memory: 40Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        seccompProfile: { type: RuntimeDefault }

        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app

    service:
      app:
        ports:
          http:
            port: *port
          metrics:
            port: 8080

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: |-
            conditions: ['[STATUS] == 200']
            group: auth
        hostnames: [ 'auth.${DOMAIN_NAME}' ]
        parentRefs:
          - name: envoy
            namespace: envoy-system

        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        type: secret
        name: authelia-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
            readOnly: true

      config-rules:
        enabled: true
        type: configMap
        name: authelia-config-rules
        globalMounts:
          - path: /config/configuration-rules.yaml
            subPath: configuration-rules.yaml
            readOnly: true
