---
# Follow https://github.com/immich-app/immich/blob/main/server/src/config.ts
# https://github.com/immich-app/immich/blob/main/docs/docs/install/config-file.md

ffmpeg:
  accel: disabled
  accelDecode: false
  acceptedAudioCodecs:
    - aac
    - mp3
    - libopus
  acceptedContainers:
    - mov
    - ogg
    - webm
  acceptedVideoCodecs:
    - h264
  bframes: -1
  cqMode: auto
  crf: 23
  gopSize: 0
  maxBitrate: '0'
  preferredHwDevice: auto
  preset: ultrafast
  refs: 0
  targetAudioCodec: aac
  targetResolution: '720'
  targetVideoCodec: h264
  temporalAQ: false
  threads: 0
  tonemap: reinhard # hable, mobius, reinhard, disabled
  transcode: required
  twoPass: false

backup:
  database:
    enabled: false

job:
  backgroundTask:
    concurrency: 10
  smartSearch:
    concurrency: 5
  metadataExtraction:
    concurrency: 10
  faceDetection:
    concurrency: 5
  search:
    concurrency: 5
  sidecar:
    concurrency: 5
  library:
    concurrency: 5
  migration:
    concurrency: 5
  thumbnailGeneration:
    concurrency: 10
  videoConversion:
    concurrency: 1
  notifications:
    concurrency: 5
  ocr:
    concurrency: 4

logging:
  enabled: true
  level: log

machineLearning:
  enabled: true
  urls:
    - http://immich-machine-learning:3003
  clip:
    enabled: true
    modelName: ViT-B-16-SigLIP-384__webli # ViT-B-32__openai
  duplicateDetection:
    enabled: true
    maxDistance: 0.01 # 0.001-0.1
  facialRecognition:
    enabled: true
    modelName: antelopev2 # buffalo_l
    minScore: 0.7  # 0-1
    maxDistance: 0.6 # 0-2
    minFaces: 4 # 2
  ocr:
    enabled: true
    modelName: PP-OCRv5_server # PP-OCRv5_mobile
    maxResolution: 736
    minDetectionScore: 0.5
    minRecognitionScore: 0.8
  availabilityChecks:
    enabled: true
    interval: 30000
    timeout: 2000

metadata:
  faces:
    import: true

reverseGeocoding:
  enabled: true

oauth:
  autoLaunch: false
  autoRegister: true
  buttonText: Login with OAuth
  enabled: true
  issuerUrl: 'https://auth.${DOMAIN_NAME}'
  clientId: '{{ .IMMICH_OAUTH_CLIENT_ID }}'
  clientSecret: '{{ .IMMICH_OAUTH_CLIENT_SECRET }}'
  signingAlgorithm: RS256
  mobileOverrideEnabled: false
  mobileRedirectUri: ''
  # profileSigningAlgorithm: none
  # roleClaim: immich_role
  scope: openid profile email
  storageLabelClaim: preferred_username
  storageQuotaClaim: immich_quota
  defaultStorageQuota: 0
  # timeout: 30000
  # tokenEndpointAuthMethod: client_secret_post

passwordLogin:
  enabled: false

storageTemplate:
  enabled: true
  hashVerificationEnabled: true
  template: '{{ `"{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"` }}'

image:
  thumbnail:
    format: webp
    size: 250
    quality: 80
  preview:
    format: jpeg
    quality: 80
    size: 1440
  fullsize:
    enabled: false
    format: jpeg
    quality: 80
  colorspace: p3
  extractEmbedded: false

newVersionCheck:
  enabled: false

trash:
  enabled: true
  days: 30

theme:
  customCss: ''

library:
  scan:
    enabled: true
    cronExpression: 0 0 * * *
  watch:
    enabled: false

server:
  externalDomain: ''
  loginPageMessage: ''
  publicUsers: true

notifications:
  smtp:
    enabled: false
    from: ''
    replyTo: ''
    transport:
      ignoreCert: false
      secure: false
      host: ''
      port: 587
      username: ''
      password: ''

user:
  deleteDelay: 7

map:
  darkStyle: https://tiles.immich.cloud/v1/style/dark.json
  enabled: true
  lightStyle: https://tiles.immich.cloud/v1/style/light.json

nightlyTasks:
  clusterNewFaces: true
  databaseCleanup: true
  generateMemories: true
  missingThumbnails: true
  startTime: '00:00'
  syncQuotaUsage: true
