---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
# Defines BGP instances and peer configurations that are applied to multiple nodes.
metadata:
  name: unifi-cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux

  bgpInstances:
    - name: instance-65100
      localASN: 65100
      peers:
        - name: unifi-ipv4
          peerASN: 64600
          autoDiscovery:
            mode: 'DefaultGateway'
            defaultGateway:
              addressFamily: ipv4
          peerConfigRef:
            name: unifi-cilium-peer

        - name: unifi-ipv6
          peerASN: 64600
          peerAddress: 2a01:e0a:2a:5552:1e0b:8bff:fe16:9435
          peerConfigRef:
            name: unifi-cilium-peer
