---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
# Defines prefixes that are injected into the BGP routing table.
metadata:
  name: lb-services
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses: [ 'LoadBalancerIP' ]
      selector:
        matchExpressions:
          - { key: io.cilium/bgp, operator: NotIn, values: [ 'deny', 'false' ] }
          - { key: io.cilium/internal, operator: NotIn, values: [ 'true' ] }
