router bgp 64600
 bgp router-id 192.168.0.1
!
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor cilium peer-group
 neighbor cilium remote-as 65100

 neighbor 192.168.42.10 peer-group cilium

!
 address-family ipv4 unicast
  neighbor cilium next-hop-self
  neighbor cilium soft-reconfiguration inbound
 exit-address-family

!
 address-family ipv6 unicast
  neighbor cilium next-hop-self
  neighbor cilium soft-reconfiguration inbound
 exit-address-family

exit
