log syslog
!
hostname UCG-Fiber
frr defaults traditional
!
router bgp 64600
  bgp router-id 192.168.0.1
  ! Uncomment the next 2 lines to disable ECMP
  ! maximum-paths 1
  ! maximum-paths ibgp 1
  no bgp ebgp-requires-policy
  no bgp default ipv4-unicast

  neighbor cilium-4 peer-group
  neighbor cilium-4 remote-as 65100
  !
  neighbor cilium-6 peer-group
  neighbor cilium-6 remote-as 65100
  !
  ! common settings applied to all neighbor in this peer group
  neighbor cilium-4 soft-reconfiguration inbound
  neighbor cilium-6 soft-reconfiguration inbound
  !
  ! IPv4 neighbor
  neighbor 192.168.42.10 peer-group cilium-4
  neighbor 192.168.42.10 description ms-01
  !
  ! IPv6 neighbor (real IPv6 address)
  neighbor ~:5a47:caff:fe7a:c6c9 peer-group cilium-6
  neighbor ~:caff:fe7a:c6c9 description ms-01
  !
  address-family ipv4 unicast
    neighbor cilium-4 activate
    neighbor cilium-4 next-hop-self
  exit-address-family
!
  address-family ipv6 unicast
    neighbor cilium-6 activate
    neighbor cilium-6 next-hop-self
  exit-address-family
!
line vty
