---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres
  annotations:
    kyverno.io/ignore: 'true'
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'

spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-9

  instances: 3
  enablePDB: true

  superuserSecret:
    name: postgres-superuser
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: '200'
      max_slot_wal_keep_size: 5GB
      shared_buffers: '128MB'

  bootstrap:
    recovery:
      source: source

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: *name

  resources:
    requests:
      memory: '512Mi'
    limits:
      hugepages-2Mi: '512Mi'

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true
