---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: trixie
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.2-standard-trixie

    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.9-standard-trixie

    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.13-standard-trixie
