---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/postgres-store
resources:
  - image-catalogs.yaml
  - secret.sops.yaml
  - cluster.yaml
  - scheduled-backup.yaml
