apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
stringData:
  username: ENC[AES256_GCM,data:dm9ZwGJ4wdw=,iv:46Gv3twRQZXLqPoqXujRDgMpa1kZ1z/WJpuzaL6DjLU=,tag:43+VKDR5HSjWfpGorALmgQ==,type:str]
  password: ENC[AES256_GCM,data:+JAaJUrc4XcipYZJK6+t7VLTSeQqJSdcU27jaicW8WPvapoz6mV+56YCyM0TPwZzBkVNoQ4b/Z3O0xQxnCmlWa1+CdzVxH/xr7qD4FfH+WOimYAtnzLMHw==,iv:Yc/JQOuZKGwCOkwAg7b5f6wHNOp77im1ZO+5+QdFo/M=,tag:Ap8y4mM3mXvnql59NjffWg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWlQvSFF0QlNNN0hEbVVu
        dkxZSUF3TitLdHBPcXY2REdsRjY4NjY4aER3CkNyRjVzd1FKOHpBb3VVZHFHRlRJ
        Ymc0RHIwUFNCY1hZWXY1d3lpbVUxbk0KLS0tIGN5cnM2b3NGbFFVM0hNelRQN2pO
        a3hGM2dlK1ZuWEZxdGsxU2VtUXVweWsKh4ANxv+om/Obx6QonvVKqdFeG+Lr+oQd
        LZFCFIZvSD3eL0BsIJyTgksvOlVMoGKQbAYs5VOusIlDeJM6sZYiIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-01T22:42:42Z"
  mac: ENC[AES256_GCM,data:d/fCTMd0ba3NY5cJw4pvuzFxp2wkt1XIOSyd/BNFq7fQP9+ldJpbeLYyyxIGKB4US7supMzCN7R7OvlYDh/i6Uw5cc+tOSClXO1ePl8/k5/lEU8CIeNIH1U5hDSTyE1JpClIdEb49ibYhZXRrEDrTQ5ZKjplWrr3lVqN/7I80So=,iv:IcPIMq5oPB4v2zqbk3CLGgP/vqzMWFceNJ9zeFwrndI=,tag:thht6bqlbOM4EjKGuRCWww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-s3-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:0aaWenLHnGHPzSTT+irakjeD,iv:+LY4+HMja0e3Qpc1UJnZ78MyKcL4gsCFzaz2b0WG9fk=,tag:4+fZKO5+AwZEb9u4pk+Ueg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:P9lA2UwbNzEEwpDXJcCFyl9JsXmR/eysM2PkeAlQU5tQ6AC3WfTBIBIuJLUQLE+FNaP9sXweFCwAS71w6IclobxexetuzSNzmRSsVWvdcLrqnivNoyRUQA==,iv:B3P9a83Q5ZXdnbJ3rDwMzDACafJRgBowJiyj2vKov/M=,tag:7kUqbQ+iGOtz8Oq7U6KmgA==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWlQvSFF0QlNNN0hEbVVu
        dkxZSUF3TitLdHBPcXY2REdsRjY4NjY4aER3CkNyRjVzd1FKOHpBb3VVZHFHRlRJ
        Ymc0RHIwUFNCY1hZWXY1d3lpbVUxbk0KLS0tIGN5cnM2b3NGbFFVM0hNelRQN2pO
        a3hGM2dlK1ZuWEZxdGsxU2VtUXVweWsKh4ANxv+om/Obx6QonvVKqdFeG+Lr+oQd
        LZFCFIZvSD3eL0BsIJyTgksvOlVMoGKQbAYs5VOusIlDeJM6sZYiIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-01T22:42:42Z"
  mac: ENC[AES256_GCM,data:d/fCTMd0ba3NY5cJw4pvuzFxp2wkt1XIOSyd/BNFq7fQP9+ldJpbeLYyyxIGKB4US7supMzCN7R7OvlYDh/i6Uw5cc+tOSClXO1ePl8/k5/lEU8CIeNIH1U5hDSTyE1JpClIdEb49ibYhZXRrEDrTQ5ZKjplWrr3lVqN/7I80So=,iv:IcPIMq5oPB4v2zqbk3CLGgP/vqzMWFceNJ9zeFwrndI=,tag:thht6bqlbOM4EjKGuRCWww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
