---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app blackbox-exporter
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/component: *app

  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true

  targetNamespace: *namespace
  path: cluster/infra/observability/blackbox-exporter
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
