---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kube-system
  - envoy-system

  - openebs-system
  - longhorn-system
  - volsync-system

  - cert-manager
  - external-secrets
  - system-upgrade
  - observability

  - operators
