---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
components:
  - ../../../components/namespace
  - ../../../components/flux/sops
  - ../../../components/flux/substituteFrom
  - ../../../components/repos/app-template
resources:
  - postgres/ks.yaml
  - app/ks.yaml
