---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prowlarr
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync

  postBuild:
    substitute:
      APP: *app
      PVC_NAME: *app
      VOLSYNC_CAPACITY: 5Gi

  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    #- name: plex

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: true

  targetNamespace: *namespace
  path: cluster/apps/media/arr/prowlarr
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
