---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/namespace
  - ../../components/flux/sops
  - ../../components/flux/substituteFrom
  - ../../components/repos/app-template
resources:
  - kube-prometheus-stack/ks.yaml
  - keda/ks.yaml

  - grafana/ks.yaml

  - kromgo/ks.yaml
  - exporters
