---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: sonarr4k-secret
    template:
      data:
        SONARR__AUTH__APIKEY: '{{ .SONARR4K_API_KEY }}'

  dataFrom:
    - extract:
        key: sonarr
