apiVersion: v1
kind: Secret
metadata:
  name: sonarr4k-secret
stringData:
  api_key: ENC[AES256_GCM,data:6Tr9URMHcD57vOTeKH06DL88ldUHid0DrYx0VF+ZgyU94ZpCY7R9cw==,iv:P0TOHVAKHFkN7RN0jTTUfgGUP5TGk8RmvIXreZZv1B0=,tag:s7DD4ICOb6hS1oHHq0Z7ww==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSy9jckpWUzhFbjRwMUxH
        NjM4R05uQTU5ci9UUGVvWVVmKzV4RjFSUkc0CnVBYncwNDZ5VXBmNmFoOXdBbk9r
        MmpQeURVN0N3Wm44OHJaQ2RqRU9BRG8KLS0tIFBJLzdDRnplczI2UDZOK2lJOHJr
        MXdRUGxXTmRUWldSUXhYT1N0UTFZREUKecKSj6xYuMWqQxOHGb50wQeG4xqjPm1a
        2f2StJAtteuBfElj+e5Z1sXnFt+zzZC/39TA9P632fJBzb7WcBOaLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T01:06:03Z"
  mac: ENC[AES256_GCM,data:8hiDNYcDMP9PTBz86XB7NsvSclmmsRalo97twvH+6xaV2WuEVCUOYBepmSPmkvPRis9wQCUdkpUQjyIH7NorrJnSOLZAl6biaiMM9X/Ojjj2UxYZyhESqgmUcInLQ8bjTMKCvlg2GEWCywH71nu5b7tkLZmPNhhDKTAe2b7arWE=,iv:kSPjRjmro5zsgDTiJse2vk2GeZMEFhAGpBf6Sj6MnaI=,tag:LSB9wJBSz07Z7VKtLujGuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
