apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:un1xYYlOysgV95a6P4z9waN+OOMJ4fkb2mJylCzXvjK2zO+0OY3ecg==,iv:j97ehikCs3nhK5iuuCDPlmlrji6WkxuwGx5k7WNBQ4c=,tag:3W7bXoJS/6pJs/QQUdZXYg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUVg3SnptOGY3dFRZTU9y
        YU01Z09VVnNUUUNUYzdCcUlwd2kyYzdrZ0EwCjgvYnRjMEx2ZFdnR3hkKytObGgr
        ZGdDdVBZOC9EVUYxeHZyT3F0ZERHcUEKLS0tIE5scWprbVM4TW5NVWlhdnRJNDZ1
        cENEOXRwdWxLeFUxK3lhWTMrUFRFWjgK/EF7N3jR+GsKJeTMF6skPahGCU1Ekn4U
        iaUl+sLeB63IDqX0M6LvihFsr+8LOjmGCKlvrq3gKZrSw5m19UVqgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T01:06:20Z"
  mac: ENC[AES256_GCM,data:LYpe0ONXXhUZGdX47YwJ6+ard2nVLRvuPZSnL3qZrEig9yoew+7oGKVRCM3ud+XQEjZ4kgsVFDNZ2nj8ex2CuL8ZeDSvmaMWsrEjblWXAy7ywZU7QhKV1m1UHI3Gdk4iivIv2wHyWOIp218s02YImu7olOc68k1iaO9mVq+I+SQ=,iv:1LlG95NM/JvIKMCh3hUPQ1VlgZ38+gPV5lkL3kJHEGg=,tag:wugcgF+hDQP8kCG6c/f1ZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
