---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      ollama:
        type: deployment
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.12.9

            env:
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: '*'

              OLLAMA_MODELS: &pvc /models
              OLLAMA_LOAD_TIMEOUT: 10m

            resources:
              requests:
                memory: 6G
                cpu: 500m
                nvidia.com/gpu: 1
              limits:
                memory: 6G
                nvidia.com/gpu: 1

        pod:
          runtimeClassName: nvidia

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.feature.node.kubernetes.io/gpu
                        operator: In
                        values:
                          - 'true'

          nodeSelector:
            nvidia.feature.node.kubernetes.io/gpu: 'true'

    service:
      app:
        ports:
          http:
            port: &port 11434

    route:
      app:
        hostnames: [ 'ollama.talos.${DOMAIN_NAME}' ]
        parentRefs:
          - name: envoy
            namespace: envoy-system

    persistence:
      data:
        existingClaim: ollama-data-pvc
        advancedMounts:
          ollama:
            app:
              - path: /.ollama

      models:
        existingClaim: ollama-models-pvc
        advancedMounts:
          ollama:
            app:
              - path: *pvc

      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
