---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: ai
spec:
  prune: true
  interval: 1h
  path: cluster/apps/ai/ollama
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
