---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: immich
spec:
  dependsOn:
    - name: postgres-immich

  prune: true
  interval: 1h
  path: cluster/apps/self-hosted/immich/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
