---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs-system # Required for Renovate lookups
spec:
  interval: 12h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chart:
    spec:
      chart: openebs
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs-system

  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
        basePath: &hostPath /var/lib/local/openebs/local

      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath

      helperPod:
        image:
          registry: quay.io/

    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false

    zfs-localpv:
      enabled: false

    lvm-localpv:
      enabled: false

    mayastor:
      enabled: false

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
