---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - plex/ks.yaml

  - plex-auto-languages/ks.yaml
  - plex-image-cleanup/ks.yaml

  - seer/ks.yaml
  - tautulli/ks.yaml

  - arr
