---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-gitlab-secret
    template:
      data:
        # tokens to reduce the impact of rate limits
        RENOVATE_GITHUB_COM_TOKEN: '{{ .RENOVATE_GITHUB_COM_TOKEN }}'
        DOCKER_HUB_USER: '{{ .DOCKER_HUB_USER }}'
        DOCKER_HUB_PASSWORD: '{{ .DOCKER_HUB_PASSWORD }}'

        # s3 storage
        RENOVATE_S3_ENDPOINT: http://nas.minio-system.svc.cluster.local:9000
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
        RENOVATE_S3_PATH_STYLE: 'true'

        # renovate bot
        RENOVATE_GITLAB_PAT: '{{ .RENOVATE_GITLAB_PAT }}'
        RENOVATE_GIT_AUTHOR: '{{ .RENOVATE_GIT_AUTHOR }}'
        RENOVATE_GIT_PRIVATE_KEY: '{{ .RENOVATE_GIT_PRIVATE_KEY }}'

        RENOVATE_REPOSITORY_CACHE: 'enabled'
        RENOVATE_REPOSITORY_CACHE_TYPE: 's3://renovate/cache-operator/'

        RENOVATE_REPORT_TYPE: 's3'
        RENOVATE_REPORT_PATH: 's3://renovate/report-operator/'

        # cache lookup using redis
        RENOVATE_REDIS_URL: 'redis://renovate-dragonfly:6379/0'
        #RENOVATE_REDIS_PREFIX: ''

        RENOVATE_PAGINATE_ALL: 'true'
  dataFrom:
    - extract:
        key: renovate-gitlab
    - extract:
        key: renovate-gitlab-bot

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-gitlab-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-gitlab-webhook-secret
    template:
      data:
        webhook-token: '{{ .RENOVATE_WEBHOOK_GITLAB }}'

  dataFrom:
    - extract:
        key: renovate-gitlab
