---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app codecov
  namespace: codecov
spec:
  dependsOn:
    - name: timescaledb
      namespace: database

  postBuild:
    substitute:
      APP: *app

  prune: true
  interval: 1h
  path: cluster/apps/dev/codecov/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
