---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: &namespace cert-manager
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  interval: 1h
  timeout: 5m
  retryInterval: 2m

  prune: false # never should be deleted
  wait: false

  targetNamespace: *namespace
  path: cluster/infra/networking/cert-manager/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
