---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cluster-infra
      namespace: flux-system
  interval: 1h
  path: cluster/apps
  prune: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
        optional: false
      - name: cluster-settings
        kind: ConfigMap
        optional: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
  patches:
    - # Add Sops decryption and postBuild substitutions to child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - name: cluster-secrets
                kind: Secret
                optional: true
              - name: cluster-settings
                kind: ConfigMap
                optional: true
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: cluster/infra
  prune: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
        optional: false
      - name: cluster-settings
        kind: ConfigMap
        optional: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
  patches:
    - # Add Sops decryption.
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: sops.flux.home.arpa/disabled notin (true)

    - # Add postBuild substitutions to child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - name: cluster-secrets
                kind: Secret
                optional: false
              - name: cluster-settings
                kind: ConfigMap
                optional: true
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
