---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  decryption:
    provider: sops

  dependsOn:
    - name: cluster-infra
      namespace: flux-system

  interval: 1h
  path: cluster/apps
  prune: true
  deletionPolicy: WaitForTermination

  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system

  patches:
    - # Add Kustomization defaults for all child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          decryption:
            provider: sops
          deletionPolicy: WaitForTermination

          interval: 1h
          timeout: 5m
          retryInterval: 2m

          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: _
                spec:
                  driftDetection:
                    mode: enabled

                  install:
                    crds: CreateReplace
                    strategy:
                      name: RetryOnFailure
                  rollback:
                    cleanupOnFail: true
                    recreate: true
                  upgrade:
                    cleanupOnFail: true
                    crds: CreateReplace
                    strategy:
                      name: RemediateOnFailure
                    remediation:
                      remediateLastFailure: true
                      retries: 2
              target:
                group: helm.toolkit.fluxcd.io
                kind: HelmRelease
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization

    - # Add postBuild substitutions to child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          postBuild:
            substituteFrom:
              - name: cluster-settings
                kind: ConfigMap
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra
  namespace: flux-system
spec:
  decryption:
    provider: sops

  interval: 1h
  path: cluster/infra
  prune: true
  deletionPolicy: WaitForTermination

  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system

  patches:
    - # Add Kustomization defaults for all child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          decryption:
            provider: sops
          deletionPolicy: WaitForTermination

          interval: 1h
          timeout: 5m
          retryInterval: 2m

          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: _
                spec:
                  driftDetection:
                    mode: enabled

                  install:
                    crds: CreateReplace
                    strategy:
                      name: RetryOnFailure
                  rollback:
                    cleanupOnFail: true
                    recreate: true
                  upgrade:
                    cleanupOnFail: true
                    crds: CreateReplace
                    strategy:
                      name: RemediateOnFailure
                    remediation:
                      remediateLastFailure: true
                      retries: 2
              target:
                group: helm.toolkit.fluxcd.io
                kind: HelmRelease
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization

    - # Add postBuild substitutions to child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          postBuild:
            substituteFrom:
              - name: cluster-settings
                kind: ConfigMap
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
