kind: Secret
unifi-api-key: ENC[AES256_GCM,data:7mv88B8F5QP38XhDnbwke/XCzGx52kLCpfAijyrw1ZM=,iv:HLaXdA2mw36MQaoaIYT+qOQQS8WbthjpJ7zmT+YBnpI=,tag:bQqdGuvJt9VUtpXMxYwBIQ==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Nkh1QTBXVnNxV1F0NE56
        WkxSbHhmWmdJWkhPSy9TblhtaE8vRDNvN0JrCnV2UW5aNkFSOFhXbnlSZ1hvUkNz
        dmVxdXkrMDk2NWJQUVZFQTNxSFREMjAKLS0tIDFOV0tiVFlYcVV4OGFqRUdCOFRn
        WFM3R2NuUnRIa0ZWV1plR256NGdrN0kKCyM0oP2ryrzOLDcYEzv9A1vb61zO3Vr3
        zk8A9PkAPkBPtu2EngoD+Kk8r/lg0/bE0qhDBYYhqrapcrHnRSBSdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T02:15:55Z"
  mac: ENC[AES256_GCM,data:4YvSj5Gg4qGfKMeKQsK78kKUc96pm3KwrAvfjrDZws/rI1cCtLCbYDZGPn5zlBxIhN5FJ1l+CMAmtAqp7vCE+zum4g99gqh1+XBVrbn7P/6Mq9rJlnPdRHoMRj2nfI7HwjYSzgSKkuIcFtzzXPX/R8KRMAaZMfWhGytC+HIojTo=,iv:wsuI+dxscaNpVqFs6J9fWe1ivH/KY7H7G58/WkBES9c=,tag:4IsViQOdK91uVGsbOYcAuQ==,type:str]
  unencrypted_regex: ^(kind)$
  mac_only_encrypted: true
  version: 3.10.2
