kind: Secret
unifi-api-key: ENC[AES256_GCM,data:54E5XGz6I281ggyt9bwdC/ZSxqVWXbV6l7b8r5ioN/4=,iv:5LKGpl445/+d3C6DxDbb8AYZ5QKRFH23pC6Xo7WwKl4=,tag:OBvbOwB+NLW1guXYCLtWeg==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2swVTFEM2hndGk3RXRG
        eFJjNGQ3blJwd2JHdHJ4K2hYLzhEWlN3dFVJCm1hWUlZWnRjRytqMmRtanhQMmpM
        b1FlVXFibmZldjNhMW42NVc0NjBNaUEKLS0tIE5TenB2MVdGeDc2U1Izdjc4dm9w
        YjBWYW1xa0Q5TlJQMTBsTmxldTFVOWsKyhT1uiyFy6DrnJ5jhbjChLUiYx/G3eda
        saR6YcEJrYRqTy6Ibimmz+JFLOD7+9mYEPSn8AApC4SFWwyDEtDsEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-15T00:07:55Z"
  mac: ENC[AES256_GCM,data:wKZplTIDY5YQa2oCyLPQbi/mbhjhOCSzaNUBmjsxju5qaC8h6REKapweExzBN2Fhi4dd0MIYyUG6FygWCjfZWln3LXinzbep2wY6laDKgtG79ciUsdZrQx/DqHcPXIXeDd5lKjpiIZ0sTfU9Qw65IVaDw9fRTRMMEM/Pj0IPvfI=,iv:jj5vdNYuCJBFlfSw4zbMbSqCmHN1MPqNieeUtaYDteA=,tag:Hp47ScpI42ENjmite0vs3g==,type:str]
  unencrypted_regex: ^(kind)$
  mac_only_encrypted: true
  version: 3.10.2
