kind: Secret
unifi-api-key: ENC[AES256_GCM,data:8B54zIo6D891cL1ZBHJj9a2zCwlDji/UU5nQ0+4GP8Y=,iv:ZnEZ7Q4Zy4mL6SXptTPh3gb+CZ4M423LG6NU1Q5cQIA=,tag:WoCpaIKEyfCFlT5T1QJ71g==,type:str]
sops:
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR3hFYlZqK1h2eC9pczUx
        ZHlzS2FjZWR1U1RBWHFyZnVsKzVrS1poWVdvCnZDSzlvSmdmWDJSNEV0Y2cwelhm
        bnZOcFIrSGY5bXE4VTA4L0VSOFBQRHMKLS0tIFhEaWtYVWtmOEdrUEZPQkJ6Sldp
        eG9HT0I1K0taVHhlbnoyZ2U1bms1N0kKdu5DssYqlX/DMSbJpiKvbTsBlAhxCdo6
        rwjVFxeitS9TMcUCfY+omcLoWRb7nc9EfpgC6v10glT/Xt29+eplSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:49:43Z"
  mac: ENC[AES256_GCM,data:fG/uMfMBuDjp46zZHhGMqFFMIuk6IoueuJuy2z6LHq0hcDx/QLqymMi5+KvN/rSGWKVYrI64WyeobidTaMFdzSTUV7dZWnuKSwt7B9fPR1W9IpVsf2t+MMK8VN2ElEqIoM+SbZR8Ef/Yw6uDFeZ7FVhBxh2RlikLYzHkCkPTt3s=,iv:pj3mzFv+VEEsQBu3hrAQ1gEblB7SFynLHtf/SDJJX30=,tag:hJRaPSzW/osoaDbgs7p+JA==,type:str]
  unencrypted_regex: ^(kind)$
  mac_only_encrypted: true
  version: 3.11.0
