---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codecov
components:
  - ../../../components/namespace
  - ../../../components/flux/sops
  - ../../../components/flux/substituteFrom
resources:
  - app/ks.yaml
  - postgres/ks.yaml
