apiVersion: v1
kind: Secret
metadata:
  name: gitlab-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:aIfIz/BPHXQM8/jhZ7hnB0RCMK51ESxHHnVziMTSgFYm8fKrbbMD/w==,iv:ZZD3A2zQfqchbyVexSNBypWFnK66ErKduZ95T1YJKxc=,tag:asZMy++2TbE9Si9mM2HKLw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1euu8v7dznj6kjx28dqd4njgtxgw5thapckaptku9de3d4jrdy5nssvgcpz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTlwd2loSHhzMDl2ZFdS
        TE82SUNrUEhJOVp4UE1WQTB3T1o1VkhTbEdZClpNTFY5eVRPTDl4aXpkcU15WkxR
        WE1DYVo1dU4ydG1uUm95d1hlTCtqcjQKLS0tIFRSQVJVZmVCSTFibGF4TmxNUE9H
        Z1pDYm9yM1IvRkVERmcrRUY1SEhmNWcKtgrj9QRE+gls/aqpw+5yH0qavxDUuf8N
        hyXJE2D7JpkY/AyyXd3KbnPPXWEKx86KKecuRvl96Bm7i5bPcllGEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:57:00Z"
  mac: ENC[AES256_GCM,data:fXXXiOwj5lClCRt3pv3Qhnrb/EkTMjUwK0/ICtlZ67L8nlc+JLYR0YACB/R8wb6a4p91ad4wwLgeFwK56Oj6emhn4aBjPnWBMI9I23bZttWwaYxakK4Ze9aVAsH+BE9uF306+Nz26R1CTSvyIlTxplQyUXJgfAN10ZlosNMlD6c=,iv:4fTIB1+GzVlonpCMzwIEYen3qhmHakVPelpllAmSGAY=,tag:MoOydi9L29RCi5A8XJ3ibg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
