---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvidia-device-plugin
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.18.2
  url: oci://ghcr.io/home-operations/charts-mirror/nvidia-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nvidia-device-plugin

  values:
    runtimeClassName: nvidia

    nodeSelector:
      nvidia.feature.node.kubernetes.io/gpu: "true"

    securityContext:
      privileged: true

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.feature.node.kubernetes.io/gpu
                  operator: In
                  values:
                    - 'true'

    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
          sharing:
            timeSlicing:
              renameByDefault: false
              failRequestsGreaterThanOne: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
